### ISSUE TITLE
FR: Include Google Cloud Pub/Sub in distributed tracing

### ISSUE THREAD

**Issue by DazWilkin** [census-instrumentation/opencensus-java#1013]
Google Cloud Engineer filing on behalf of a Google Cloud customer.

Customer expects distributed tracing flows to span Google Cloud Pub/Sub service.
As favored messaging service for GCP customers, Pub/Sub is a foundational component of many customer solutions and if the service does not integrate tracing spans, this makes OpenCensus (tracing) less useful.

Customers prefers Java although this FR transcends specific runtimes and should be provided for all

Requst Java, Golang initially.

/cc: @mtwo @shahprit

**Comment by HailongWen** [comment]
Ack. I am on vacation now and might not be able to respond to this timely.

Meanwhile, @DazWilkin please refer to the integration we've done in  https://github.com/GoogleCloudPlatform/google-cloud-java/pull/2846 which demonstrated some basic ideas of how OpenCensus integrate with GCS.

**Comment by DazWilkin** [comment]
@HailingWeb Thank you! I'm leaving on vacation tomorrow but I'll pass this along to my customer and will try to find some time to investigate applying this to Pub/Sub when I return.

**Comment by bogdandrutu** [comment]
@DazWilkin can you tell me more details about this? Does this request imply pub/sub passing internally the cloud trace context and also maybe participate in the trace or just the client library instrumented?

**Comment by DazWilkin** [comment]
The customer (and others) want to be able to have traces that span services that span Pub/Sub. So, the former. E.g. App Engine receiving a client request, publishing a message to Pub/Sub that perhaps triggers a GKE service and dumps something onto Spanner.

**Comment by bogdandrutu** [comment]
@DazWilkin Awesome. This implies some internal discussions as well about instrumenting the Pub/Sub service internally correct?

**Comment by DazWilkin** [comment]
Filling this FR is a catalyst for these discussions to begin (if not already) or to help me get folded into them so that I may pursue for this (and all) customers.

**Comment by songy23** [comment]
@dinooliva Should we mark this as complete?

**Comment by songy23** [comment]
IIUC Cloud Pub-Sub integration in Java is done. Tutorial can be found at https://opencensus.io/integrations/google_cloud/google_cloud_pubsub/java/.

**Comment by deanberris** [comment]
Is there a chance that these convenience functions/types would be implemented in Go/Python?

**Comment by songy23** [comment]
@deanberris Feel free to open a feature request under https://github.com/census-instrumentation/opencensus-specs.
