### ISSUE TITLE
Sampler not working

### ISSUE THREAD

**Issue by grv0908** [census-instrumentation/opencensus-java#1015]
Please answer these questions before submitting a bug report.

### What version of OpenCensus are you using?
0.12.0

### What JVM are you using (`java -version`)?
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)

### What did you do?

Tried this [example](https://github.com/census-instrumentation/opencensus-java/blob/master/examples/src/main/java/io/opencensus/examples/trace/MultiSpansTracing.java) with zipkinTraceExporter
`ZipkinTraceExporter.createAndRegister("http://127.0.0.1:9411/api/v2/spans", "service1");`
also used 
`private static final Sampler sampler = Samplers.alwaysSample();`
`Span rootSpan = tracer.spanBuilderWithExplicitParent("RootSpan", null).setSampler(sampler).startSpan();`

### What did you expect to see?
Spans in Zipkin UI

### What did you see instead?
No Span

But if I generate around 10k spans 
`for(int i= 0; i<10000; i++) {
             doWork();
        }`

Spans can be seen in zipkin ui probably only default sampler is working

**Comment by bogdandrutu** [comment]
@grv0908 do you see 1 span or >100 spans? I am asking because we may have a different problem than the sampler which is the fact that if the application finishes fast enough we may not be able to send the data out of the task. This is still a bug but I need to know what is the behavior.

**Comment by grv0908** [comment]
@bogdandrutu Yes I am getting lot more than 100 spans.

Yes you are correct. After removing for loop I have added a `Thread.sleep()` after
`doWork()`  so now Application is getting enough time to export that single span and able to see it in Zipkin.

**Comment by bogdandrutu** [comment]
I think this can be closed now.
