### ISSUE TITLE
Add a method to check whether a StatsContext serializes to nothing.

### ISSUE THREAD

**Issue by carl-mastrangelo** [census-instrumentation/opencensus-java#104]
In https://github.com/grpc/grpc-java/blob/6ff5f2149bb643fa6cc951e42831c067003ff810/core/src/main/java/io/grpc/internal/StatsTraceContext.java#L140

We unconditionally put the stats context header in the metadata.  For many uses, this header is completely empty, and results in unnecessary allocation and processing on the Critical path for RPCs.   It would be really useful to add a method to StatsContext that indicates whether there is any data to serialize, and possibly skip adding the header.  Perhaps `hasSerializableData` ?

**Comment by carl-mastrangelo** [comment]
@zhangkun83 fyi

**Comment by dinooliva** [comment]
You should be able to check if statsCtx is equal to the default stats context (via StatsContextFactory.getDefault()) in which case you won't need to add it to the metadata.

**Comment by carl-mastrangelo** [comment]
@dinooliva this will not be sufficient.  That class is abstract, and any library can extend and override the serialize method.  Construction of those objects isn't limited to only that factory, so I don't believe that will work.

**Comment by zhangkun83** [comment]
I agree with @carl-mastrangelo. I also wanted to add that some tags, e.g., method name, are not propagated, thus there could be a case where StatsContext is not `getDefault()` but it still serializes to nothing.

**Comment by dinooliva** [comment]
The original intention was there would only ever be 1 implementation of the class in any given binary but, I agree, this is difficult to enforce.

I'll propose a new method for the API soon.

**Comment by songy23** [comment]
Obsolete.
