### ISSUE TITLE
JaegerExporterHandlerIntegrationTest is fluctuant in continuous build

### ISSUE THREAD

**Issue by songy23** [census-instrumentation/opencensus-java#1066]
For example https://ci.appveyor.com/project/opencensusjavateam/opencensus-java/build/1.0.2174.

/cc @marccarre 

> io.opencensus.exporter.trace.jaeger.JaegerExporterHandlerIntegrationTest > exportToJaeger FAILED
    org.junit.runners.model.TestTimedOutException: test timed out after 30000 milliseconds
        at java.io.WinNTFileSystem.getBooleanAttributes(Native Method)
        at java.io.File.isFile(File.java:882)
        at io.opencensus.exporter.trace.jaeger.JaegerExporterHandlerIntegrationTest.isDocker(JaegerExporterHandlerIntegrationTest.java:225)
        at io.opencensus.exporter.trace.jaeger.JaegerExporterHandlerIntegrationTest.dockerIsInstalledAndExecutable(JaegerExporterHandlerIntegrationTest.java:215)
        at io.opencensus.exporter.trace.jaeger.JaegerExporterHandlerIntegrationTest.exportToJaeger(JaegerExporterHandlerIntegrationTest.java:70)
3 tests completed, 1 failed
:opencensus-exporter-trace-jaeger:test FAILED

**Comment by songy23** [comment]
JaegerExporterHandlerIntegrationTest.[dockerIsInstalledAndExecutable()](https://github.com/census-instrumentation/opencensus-java/blob/master/exporters/trace/jaeger/src/test/java/io/opencensus/exporter/trace/jaeger/JaegerExporterHandlerIntegrationTest.java#L207) scans all PATH files and directories, which could be very slow.

Meanwhile the test has a time out of [only 3 seconds](https://github.com/census-instrumentation/opencensus-java/blob/master/exporters/trace/jaeger/src/test/java/io/opencensus/exporter/trace/jaeger/JaegerExporterHandlerIntegrationTest.java#L68).

**Comment by marccarre** [comment]
Given the goal is to find whether Docker is running or not, I could simply check the status code of `docker -v`, return `true` if zero, return `false` otherwise or if an exception has been thrown.
This would be `O(1)`. WDYT?

**Comment by songy23** [comment]
That sounds good to me :)

/cc @HailongWen

**Comment by marccarre** [comment]
I just confirmed this also work with Docker for Windows under a Windows shell (notice `at java.io.WinNTFileSystem.getBooleanAttributes(Native Method)`).

**Comment by songy23** [comment]
Saw another failure here: https://travis-ci.org/census-instrumentation/opencensus-java/jobs/356964586#L2034

> io.opencensus.exporter.trace.jaeger.JaegerExporterHandlerIntegrationTest > exportToJaeger FAILED
    java.lang.AssertionError: 
    Expected: is <1>
         but: was <0>
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.junit.Assert.assertThat(Assert.java:923)
        at io.opencensus.exporter.trace.jaeger.JaegerExporterHandlerIntegrationTest.exportToJaeger(JaegerExporterHandlerIntegrationTest.java:135)

This one looks different.

**Comment by marccarre** [comment]
1. @songy23, this doesn't look like the right link. Where did you see this failure?
    I _think_ I was nevertheless able to reproduce it by removing my local Docker image and letting the test download a fresh one:

        ## Before: integration test passing.

        $ docker rmi jaegertracing/all-in-one
        Untagged: jaegertracing/all-in-one:latest
        Untagged: jaegertracing/all-in-one@sha256:117aaade00f7915ed6f28383354ad2f0b210085b65f3049f7d176d943864e00c
        Deleted: sha256:c27493a6554a3591802fcdf94c5f733664b8c89a2b7d661de214e541de9a27f5
        Deleted: sha256:740e5ae6f433a17b5a20edd512639b08e8c0241f99e3244892c0d2e9ffbe3ba8
        Deleted: sha256:2e019f57d6a070443db7c86d1e194932ca5bfc528fa2592e762ea664affd78b8

        ## After: integration test failing with a similar error, but at a slightly different line (#131).

    This means it was a genuine error the integration test caught.

    According to [that page](https://hub.docker.com/r/jaegertracing/all-in-one/tags/), there doesn't seem to be a new release of Jaeger, however, we can see that `latest` was updated recently (_14 hours ago_), so they may have a new RC or `latest` may be whatever `master` yields.

    Would you rather:

      - a. run [`latest`](https://github.com/census-instrumentation/opencensus-java/blob/master/exporters/trace/jaeger/src/test/java/io/opencensus/exporter/trace/jaeger/JaegerExporterHandlerIntegrationTest.java#L74) at the risk of having the build less stable, but catching such failures? **(current state)**, or 
      - b. lock the version used for integration testing, which may be less confusing, but miss such failures? or
      - c. test for multiple, _static_, locked versions of Jaeger, which would catch such failure, be explicit, be stable, but take longer to run, and one would have to periodically add new versions/change the range of versions we test against? or
      - d. test for multiple, _dynamic_, locked versions of Jaeger, which would catch such failure, be explicit, be stable, but take longer to run than a. and b., and be more complex than c.? (_dynamic_ because we would fetch Jaeger's valid versions automatically at https://hub.docker.com/r/jaegertracing/all-in-one/tags/) 

1. I can see https://travis-ci.org/census-instrumentation/opencensus-java/jobs/357147554 failed with:

        io.opencensus.exporter.trace.jaeger.JaegerExporterHandlerIntegrationTest > exportToJaeger FAILED
            java.net.ConnectException: Connection refused (Connection refused)
                at java.net.PlainSocketImpl.socketConnect(Native Method)
                [...]

    but difficult to know whether we didn't wait long enough, or the container failed to start.
    I'd be grateful if you can share more details. I'll see whether I can improve this in the meantime anyway.

3. I've also improved the pre-condition for running the integration test in #1083 as I realised `docker -v` wasn't exactly doing what I thought it would do.

**Comment by songy23** [comment]
@marccarre I re-ran the build so probably the log got overwritten, but I think it matches the reproduced output on your local Docker image.

I think starting with option b sounds better, we can always switch to multiple or dynamic docker version later if that's 100% necessary. /cc @HailongWen @sebright WDYT?

Besides, I just saw another Connection reset error in the build [here](https://travis-ci.org/census-instrumentation/opencensus-java/jobs/357273057#L2046).

**Comment by sebright** [comment]
Starting with option b sounds good to me, especially if "latest" can refer to an unreleased version.  Are there likely to be incompatibilities that only appear when we test with a range of Jaeger versions?

**Comment by HailongWen** [comment]
It sounds better to start with option b for now. Though I think we are starting to get a little bit too deep into it.

My thought on the integration is that it should be placed somewhere else (e.g. opencensus-experiments) and more importantly, the CI system should help with setting up the test environment. In a dedicated integration test we could have settings on different versions of OS, JDK, docker as well as Jaeger.

**Comment by marccarre** [comment]
> Are there likely to be incompatibilities that only appear when we test with a range of Jaeger versions?

Being a new user myself, I'm afraid I'm not close enough to the Jaeger project to be able to answer this question, and tell if they are planning major changes, if there already are discrepancies between versions, etc. That being said, the integration test caught a discrepancy against `latest`, so one of these could be eventually released, accidentally or not.

**Comment by songy23** [comment]
Reopen, this issue is happening again in MacOS build (e.g [build](https://source.cloud.google.com/results/invocations/f93d1eda-2a90-446c-ab5d-c3ef30ca6826/targets/opencensus%2Fjava%2Fpresubmit%2Fmacos/log)):

```
io.opencensus.exporter.trace.jaeger.JaegerExporterHandlerIntegrationTest > exportToJaeger FAILED
    java.lang.AssertionError: Not true that <0> is equal to <1>
        at io.opencensus.exporter.trace.jaeger.JaegerExporterHandlerIntegrationTest.exportToJaeger(JaegerExporterHandlerIntegrationTest.java:146)
        Caused by:
        java.lang.AssertionError: Not true that <0> is equal to <1>
            at com.google.common.truth.FailureStrategy.fail(FailureStrategy.java:28)
            at com.google.common.truth.FailureStrategy.fail(FailureStrategy.java:22)
            at com.google.common.truth.Subject.failComparingToStrings(Subject.java:335)
            at com.google.common.truth.Subject.doEqualCheck(Subject.java:127)
            at com.google.common.truth.Subject.isEqualTo(Subject.java:104)
            ... 1 more
3 tests completed, 1 failed
```
