### ISSUE TITLE
OpenCensus API depends on Guava collections

### ISSUE THREAD

**Issue by ericgribkoff** [census-instrumentation/opencensus-java#1068]
This (unnecessarily?) increases APK size and method count for gRPC Android users. The `com.google.common.collect` dependencies brought in by OpenCensus are slightly larger than the `io.opencensus` code itself that gets included in classes.dex after proguard is run, and 10% of the size of the gRPC library itself, and introduce ~400 new method references.

It looked (at a quick glance) like the use of `com.google.common.collect` in opencensus-api is fairly shallow and wouldn't be too hard to remove, which would help downstream gRPC Android users. Would removing the use of `com.google.common.collect` introduce any problems for the OpenCensus library?

**Edit** gRPC Java does depend on Guava, but avoids use of collections, which lets those get stripped out. Updated the issue title/description to reflect that it's only half of the total impact of Guava on the APK size which would be better avoided. See https://github.com/grpc/grpc-java/pull/2208 for prior art in grpc-java around removing use of Guava collections.

**Comment by songy23** [comment]
Fixed by https://github.com/census-instrumentation/opencensus-java/pull/1069.
