### ISSUE TITLE
Remove Guava from opencensus-api?

### ISSUE THREAD

**Issue by saturnism** [census-instrumentation/opencensus-java#1081]
Please answer these questions before submitting a bug report.

### What version of OpenCensus are you using?
0.12.x

### What did you expect to see?
opencensus-api has dependency on Guava. I don't know how Guava is actually used by the API, but it's strange for an API module to have explicit dependency on Guava that may actually introduce dependency conflicts for users.

In fact, if Guava is not used extensively, it's probably better not to use it at all, or, shade it to avoid issues.

**Comment by saturnism** [comment]
Also, here is a dependency tree on using OpenCensus. I wonder if they are all necessary to expose to the end user.

```
[INFO] com.example:census-example:jar:1.0-SNAPSHOT
[INFO] +- io.opencensus:opencensus-api:jar:0.12.2:compile
[INFO] |  +- com.google.errorprone:error_prone_annotations:jar:2.2.0:compile
[INFO] |  +- com.google.code.findbugs:jsr305:jar:3.0.1:compile
[INFO] |  +- io.grpc:grpc-context:jar:1.9.0:compile
[INFO] |  \- com.google.guava:guava:jar:19.0:compile
[INFO] +- io.opencensus:opencensus-impl:jar:0.12.2:runtime
[INFO] |  +- io.opencensus:opencensus-impl-core:jar:0.12.2:runtime
[INFO] |  \- com.lmax:disruptor:jar:3.3.9:runtime
[INFO] +- io.opencensus:opencensus-exporter-stats-prometheus:jar:0.12.2:compile
[INFO] +- io.prometheus:simpleclient:jar:0.3.0:compile
[INFO] +- io.prometheus:simpleclient_hotspot:jar:0.3.0:compile
[INFO] +- io.prometheus:simpleclient_httpserver:jar:0.3.0:compile
[INFO] |  \- io.prometheus:simpleclient_common:jar:0.3.0:compile
[INFO] \- io.opencensus:opencensus-exporter-trace-zipkin:jar:0.12.2:compile
[INFO]    +- io.zipkin.reporter2:zipkin-reporter:jar:2.3.2:compile
[INFO]    |  \- io.zipkin.zipkin2:zipkin:jar:2.4.6:compile
[INFO]    \- io.zipkin.reporter2:zipkin-sender-urlconnection:jar:2.3.2:compile
```

**Comment by sebright** [comment]
@saturnism Which dependencies are you referring to in the graph above?  It looks like it includes an OpenCensus implementation and exporters in addition to the API library.

I think that it wouldn't be too difficult to remove Guava from opencensus-api.  We already removed the dependency on Guava collections in #1068.

**Comment by adriancole** [comment]
you didn't ask me but io.prometheus:simpleclient is a liability as it is a pre-release api version
com.lmax:disruptor should probably be shaded (assuming it works ok shaded)

**Comment by adriancole** [comment]
io.prometheus:simpleclient liability because it could conflict with other versions of this, and assuming that 0.3 means api changes are likely

**Comment by songy23** [comment]
@adriancole I tried to upgrade to `io.prometheus:simpleclient` v0.3.0 before and I think it is backwards compatible, though it has some issues on our CI build on JDK 8 and 9 (https://github.com/census-instrumentation/opencensus-java/pull/1051).

**Comment by saturnism** [comment]
@sebright i simply created a new project that uses opencensus, and generated a dependency tree from there.

`opencensus-api` has dependency on `guava`, and also exports a few others like errorprone and findbugs annotations. I'm not sure if those need to be exported to user runtime?

+1 to @adriancole for shading disruptor.

**Comment by bogdandrutu** [comment]
+1 for the shading of the disruptor and probably all dependencies that can. One downside of doing this is the increase in the application binary size but probably should be fine.

**Comment by sebright** [comment]
If I understand correctly, we should be able to make the Error Prone and FindBugs dependencies `compileOnly`.

**Comment by sebright** [comment]
I made a PR to make the annotation libraries `compileOnly`: #1098

**Comment by sebright** [comment]
After #1111, there are only two uses of Guava left in the API.  When we finish removing it, we should add a note about the project's dependency policy to CONTRIBUTING.md.

**Comment by sebright** [comment]
There is another suggestion related to this issue in https://github.com/census-instrumentation/opencensus-java/pull/1111#issuecomment-378439633.

**Comment by adriancole** [comment]
>
> There is another suggestion related to this issue in #1111 (comment)
> <https://github.com/census-instrumentation/opencensus-java/pull/1111#issuecomment-378439633>
> .
>
yep TL;DR; base16 is not a good reason to keep a dep on guava. Implementing
base16 is trivial and it doesn't change. just do it (as nike likes to say)

**Comment by sebright** [comment]
Unassigning myself, since I'm switching projects.
