### ISSUE TITLE
Wrong Mail ID

### ISSUE THREAD

**Issue by vettyvignesh** [census-instrumentation/opencensus-java#1088]
The mail ID listed seems to be wrong. Whenever I try to send a mail, all I get back is "failed to deliver message"

**Comment by bogdandrutu** [comment]
Can you be more specific, where is listed and what email id did you see?

**Comment by vettyvignesh** [comment]
The ID on [main page](https://github.com/census-instrumentation) of the repository, i.e ,  census-developers@googlegroups.com

**Comment by songy23** [comment]
@tags07 What should be the correct email alias for contacting OC developers?

**Comment by tags07** [comment]
Could you please try again? I just tested it as a non-member and was able to receive the email.

**Comment by vettyvignesh** [comment]
It seems to have been sorted now,
