### ISSUE TITLE
Stats record API should allow "extra_tags"

### ISSUE THREAD

**Issue by bogdandrutu** [census-instrumentation/opencensus-java#1103]
We should allow users to add extra tags in the record API call to avoid cases like:
```
try(Scope s = AddTags(...)) {
  Record(...);
}
```

**Comment by songy23** [comment]
We have [MeasureMap.record(TagContext tags)](https://github.com/census-instrumentation/opencensus-java/blob/master/api/src/main/java/io/opencensus/stats/MeasureMap.java#L71), which allows users to put additional tags when recording without propagating them.
