### ISSUE TITLE
HTTP Attributes are not mapped in Stackdriver exporter

### ISSUE THREAD

**Issue by Sebruck** [census-instrumentation/opencensus-java#1153]
Please answer these questions before submitting a bug report.

### What version of OpenCensus are you using?
0.12.3

### What JVM are you using (`java -version`)?
8

### What did you do?
Adding http attributes according to the [spec](https://github.com/census-instrumentation/opencensus-specs/blob/master/trace/HTTP.md) to a span (http.host, http.method, ...), see here: https://github.com/Sebruck/opencensus-scala/blob/master/akka-http/src/main/scala/com/github/sebruck/opencensus/akka/http/trace/HttpAttributes.scala#L16

### What did you expect to see?
The spec defines that those attributes should be mapped when exporting to stackdriver, e.g.:
`http.host` -> `/http/host`

But this seems not to happen, in Stackdriver I still see the initial value.

I also can't find any code doing this in the `opencensus-exporter-trace-stackdriver` module.

### What did you see instead?
The attributes should be mapped as defined in the specs.

Is this a missing feature or a bug?

**Comment by Sebruck** [comment]
If it's a missing feature I'd be happy to contribute.

**Comment by sebright** [comment]
I think this is a missing feature, and we would be happy to accept a contribution!
