### ISSUE TITLE
Prometheus Histogram Bucket Boundaries Missing

### ISSUE THREAD

**Issue by tzwickl** [census-instrumentation/opencensus-java#1164]
### What version of OpenCensus are you using?

0.13.0

### What JVM are you using (`java -version`)?
 
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

### What did you do?
I used the [QuickStart.java](https://github.com/census-instrumentation/opencensus-java/blob/master/examples/src/main/java/io/opencensus/examples/helloworld/QuickStart.java) example and added the following lines of code to export the metrics to Prometheus:

    // Creates a PrometheusStatsCollector and registers it to the default Prometheus registry.
    PrometheusStatsCollector.createAndRegister();

    // Uses a simple Prometheus HTTPServer to export metrics.
    // You can use a Prometheus PushGateway instead, though that's discouraged by Prometheus:
    // https://prometheus.io/docs/practices/pushing/#should-i-be-using-the-pushgateway.
    try {
      io.prometheus.client.exporter.HTTPServer server = new HTTPServer(/*host*/ "localhost", /*port*/  9091, /*daemon*/ true);
    } catch (IOException e) {
      e.printStackTrace();
    }

### What did you expect to see?

If I access now the metrics page from Prometheus (http://localhost:9091/metrics) I expect to see:

```
# HELP opencensus_my_org_views_video_size Opencensus Prometheus metrics: processed video size over time
# TYPE opencensus_my_org_views_video_size histogram
opencensus_my_org_views_video_size_bucket{my_org_keys_frontend="mobile-ios9.3.5",le="...",} 0.0
opencensus_my_org_views_video_size_bucket{my_org_keys_frontend="mobile-ios9.3.5",le="..."} 0.0
opencensus_my_org_views_video_size_bucket{my_org_keys_frontend="mobile-ios9.3.5",le="..."} 1.0
opencensus_my_org_views_video_size_bucket{my_org_keys_frontend="mobile-ios9.3.5",le="..."} 0.0
opencensus_my_org_views_video_size_count{my_org_keys_frontend="mobile-ios9.3.5",} 1.0
opencensus_my_org_views_video_size_sum{my_org_keys_frontend="mobile-ios9.3.5",} 2.62144E7
```

### What did you see instead?

```
# HELP opencensus_my_org_views_video_size Opencensus Prometheus metrics: processed video size over time
# TYPE opencensus_my_org_views_video_size histogram
opencensus_my_org_views_video_size_bucket{my_org_keys_frontend="mobile-ios9.3.5",} 0.0
opencensus_my_org_views_video_size_bucket{my_org_keys_frontend="mobile-ios9.3.5",} 0.0
opencensus_my_org_views_video_size_bucket{my_org_keys_frontend="mobile-ios9.3.5",} 1.0
opencensus_my_org_views_video_size_bucket{my_org_keys_frontend="mobile-ios9.3.5",} 0.0
opencensus_my_org_views_video_size_count{my_org_keys_frontend="mobile-ios9.3.5",} 1.0
opencensus_my_org_views_video_size_sum{my_org_keys_frontend="mobile-ios9.3.5",} 2.62144E7
```

So I'm missing the `le` tags in the bucket which specify the boundaries... When I open the Prometheus CLI the metric `opencensus_my_org_views_video_size_bucket` shows always 0 and I don't see any histogram data...

**Comment by songy23** [comment]
Hi Thomas, 

Thanks for pointing this out! Prometheus has a built-in `Histogram` metric type, which requires the user to set bucket boundaries when creating `Histogram`s. In this case, the bucket boundaries will be automatically appended as the `le` tag. 

However, for our OpenCensus Prometheus exporter, we export stats as generic `Sample`s (`Histogram` is a built-in subclass of `Sample`), so the bucket boundaries won't be set by default. I didn't realize we could manually add the `le` tag though - I'll try that and see how it works.
