### ISSUE TITLE
Prometheus Stats exporter: Remove namespace and help message (or make it configurable)

### ISSUE THREAD

**Issue by Sebruck** [census-instrumentation/opencensus-java#1202]
When exporting stats via the prometheus exporter currently every metic is prefixed by `opencensus` and every help message with `Opencensus Prometheus metrics: `.

I think this is bad for several reasons:
- We already use the prometheus java client, when we now want to switch to opencensus, all our current metrics are screwed since they do not have the `opencensus` prefix.
- This kind of leaks implementation details to the outside. IMHO it shouldn't be present in the metrics which library I use to collect my metrics.

See: https://github.com/census-instrumentation/opencensus-java/blob/3838c4c4b150fad4e10671c9e37f36c894a9c535/exporters/stats/prometheus/src/main/java/io/opencensus/exporter/stats/prometheus/PrometheusExportUtils.java#L86

WDYT?

**Comment by songy23** [comment]
Yes we can definitely do that. OC Go already removed the namspace in https://github.com/census-instrumentation/opencensus-go/pull/665, I'll post a PR to remove it for Java.
