### ISSUE TITLE
Update gRPC to use the new RPC constants, and record against the new ones

### ISSUE THREAD

**Issue by songy23** [census-instrumentation/opencensus-java#1207]
We need to update gRPC to use the latest OpenCensus version, and record against the new RPC constants (defined in https://github.com/census-instrumentation/opencensus-java/pull/1115). 

Note that gRPC also needs to record stats for the deprecated constants, for backwards compatibility.

**Comment by sebright** [comment]
It looks like https://github.com/grpc/grpc-java/pull/4494 handles this issue.

**Comment by bogdandrutu** [comment]
grpc PR was merged.
