### ISSUE TITLE
Stats: Recording the same measure in one MeasureMap multiple times does not work

### ISSUE THREAD

**Issue by Sebruck** [census-instrumentation/opencensus-java#1213]
Please answer these questions before submitting a bug report.

### What version of OpenCensus are you using?
0.13.2

### What JVM are you using (`java -version`)?
8

### What did you do?
I record the same measure multiple times in one MeasureMap. 

(Sorry for the scala reproducer)

```scala
import java.io.{StringWriter, Writer}

import io.opencensus.exporter.stats.prometheus.PrometheusStatsCollector
import io.opencensus.stats.Aggregation.Sum
import io.opencensus.stats.{Measure, Stats, View}
import io.prometheus.client.Collector.MetricFamilySamples
import io.prometheus.client.CollectorRegistry
import io.prometheus.client.exporter.common.TextFormat

import scala.collection.JavaConverters._

object Reproducer extends App {
  PrometheusStatsCollector.createAndRegister()

  val viewManager   = Stats.getViewManager
  val statsRecorder = Stats.getStatsRecorder

  val measure = Measure.MeasureLong.create("myMeasure", "desc", "u")
  val view = View.create(View.Name.create("myView"),
                         "desc",
                         measure,
                         Sum.create(),
                         List.empty.asJava)

  viewManager.registerView(view)
  statsRecorder.newMeasureMap().put(measure, 2L).put(measure, 3L).record()

  // Print Prometheus to show the result
  val samples = CollectorRegistry.defaultRegistry.metricFamilySamples()

  private def toPrometheusTextFormat(
      samples: java.util.Enumeration[MetricFamilySamples]): String = {
    val writer: Writer = new StringWriter()
    TextFormat.write004(writer, samples)
    writer.toString
  }
  Thread.sleep(5000)
  println(toPrometheusTextFormat(samples))
}
```

### What did you expect to see?
The view `myView` to have value `5`

### What did you see instead?
```
# HELP opencensus_myView Opencensus Prometheus metrics: desc
# TYPE opencensus_myView untyped
opencensus_myView 3.0
``` 

I guess this is a bug, or?

**Comment by Sebruck** [comment]
Just saw in the java doc: 

```   * Associates the {@link MeasureDouble} with the given value. Subsequent updates to the same
   * {@link MeasureDouble} will overwrite the previous value.```

So it's intended and not a bug. Does it still makes sense to support this? Or throw an exception if one puts the same measure a second time into the map?

**Comment by sebright** [comment]
@Sebruck Yes, that is the intended behavior.  I think we didn't support recording multiple values for the same measure because we didn't know of a use case, and knowing that there is only one value per measure could allow a more efficient implementation.

Do you have a use case for recording multiple values?  If we continue to not support recording multiple values, I think it makes sense to throw an exception if one is overwritten.  The sequence of recorded measures should be static in most cases, so having a call to `put` that is always ignored would likely be a bug in the instrumented code.

**Comment by songy23** [comment]
Not specifically object to this but something to think about: I though when we first designed the `MeasureMap` class, we wanted it to have similar behavior to Java `Map`s (that's also why we named it `Map`). I'm not sure throwing exceptions for overwriting entries is the best practice here, this could be confusing to users who think of `MeasureMap` as a `Map`.

**Comment by sebright** [comment]
Yeah, the existing name could be misleading if we changed the behavior.  We could add a new class, which would also make the change more backwards compatible.

**Comment by Sebruck** [comment]
@songy23 from a user point of view I totally didn't get/thought about the analogy to the behaviour of a Java Map.

**Comment by songy23** [comment]
@Sebruck Yes - that (overwriting entries for `MeasureMap.put()`) is our initial intention as developer, and I understand it may be confusing to users :)

My point is maybe it's fine to keep the existing behavior, and have better documentation to let users realize that `MeasureMap.put()` is intended to behave the same way to `Map.put()`. Again, I'm also fine with throwing exceptions if `put` is called multiple times, as long as we have clear documentation for it.

**Comment by songy23** [comment]
Kind of an intended behavior, we may revisit this in the design of merged APIs.
