### ISSUE TITLE
exporter/stats/Stackdriver: spamming from ExportStatsToStackdriver in traces

### ISSUE THREAD

**Issue by odeke-em** [census-instrumentation/opencensus-java#1218]
Idly running a Java server instrumented with OpenCensus and Stackdriver stats spams the traces with a bunch of outlier and high latency traces `ExportStatsToStackdriver` which highly distort the trace views when included with other traces.

For example, for traces that normally are in the 1ms range see what this looks like, the usual >100ms `ExportStatsToStackdriver` distort the output but also spam it
![screen shot 2018-05-30 at 12 12 55 pm](https://user-images.githubusercontent.com/4898263/40742290-e2f1ae0e-6402-11e8-9f61-15a5c29494e2.png)

Idly running:
![screen shot 2018-05-30 at 12 09 48 pm](https://user-images.githubusercontent.com/4898263/40742153-6d564d80-6402-11e8-808f-8bc1941dd7de.png)
![screen shot 2018-05-30 at 12 10 07 pm](https://user-images.githubusercontent.com/4898263/40742166-74c23e4e-6402-11e8-910b-bf1a816c32ee.png)

You can reproduce this by running this simple project https://github.com/orijtech/opencensus-for-grpc-java-developers
```shell
GOOGLE_APPLICATION_CREDENTIALS=~/Downloads/census-demos-237a8e1e41df.json mvn exec:java -Dexec.mainClass=io.ocgrpc.capitalize.CapitalizeServer
```

**Comment by songy23** [comment]
@odeke-em thanks for catching this. I added the span to instrument Stackdriver stats exporter in https://github.com/census-instrumentation/opencensus-java/pull/898, by that time the trace `ExportStatsToStackdriver` should have default sampling probability. However we changed some logic later and now all the `ExportStatsToStackdriver` traces will be sampled. I'll post a PR to restore it to default sampling probability.

**Comment by odeke-em** [comment]
Great, thanks @songy23 for the quick response!

Also I just noticed that there is one too for Prometheus `ExportStatsToPrometheus`
![screen shot 2018-05-30 at 12 31 40 pm](https://user-images.githubusercontent.com/4898263/40743123-80010a76-6405-11e8-8487-9adf0139452e.png)

Also doesn't the Scoped span in the try-with-resources in that PR mean that no support for Java 6 and below?

**Comment by songy23** [comment]
Yep, the span that instruments Prometheus is also fixed in https://github.com/census-instrumentation/opencensus-java/pull/1219. And yes, Java 7 or above is required for all stats exporters: [Prometheus](https://github.com/census-instrumentation/opencensus-java/tree/master/exporters/stats/prometheus#java-versions), [Stackdriver](https://github.com/census-instrumentation/opencensus-java/tree/master/exporters/stats/stackdriver#java-versions)

**Comment by odeke-em** [comment]
Cool thanks @songy23!
