### ISSUE TITLE
exporter/stats/StackdriverExporter: Exception thrown when creating MetricDescriptor. java.lang.NoSuchMethodError: com.google.common.base.Throwables.throwIfInstanceOf(Ljava/lang/Throwable;Ljava/lang/Class;)V

### ISSUE THREAD

**Issue by odeke-em** [census-instrumentation/opencensus-java#1220]
When running a demo after instrumenting a Redis Java client https://gist.github.com/odeke-em/69f750885095ce50cbc409a2386495d9 with the diff at https://github.com/orijtech/jedis/pull/1 (in case you'd like to inspect the metrics or reproduce), I get back this crash in my server
```shell
May 30, 2018 2:35:26 PM io.opencensus.exporter.stats.stackdriver.StackdriverExporterWorker registerView
WARNING: Exception thrown when creating MetricDescriptor.
java.lang.NoSuchMethodError: com.google.common.base.Throwables.throwIfInstanceOf(Ljava/lang/Throwable;Ljava/lang/Class;)V
	at com.google.api.gax.rpc.ApiExceptions.callAndTranslateApiException(ApiExceptions.java:54)
	at com.google.api.gax.rpc.UnaryCallable.call(UnaryCallable.java:112)
	at com.google.cloud.monitoring.v3.MetricServiceClient.createMetricDescriptor(MetricServiceClient.java:747)
	at io.opencensus.exporter.stats.stackdriver.StackdriverExporterWorker.registerView(StackdriverExporterWorker.java:134)
	at io.opencensus.exporter.stats.stackdriver.StackdriverExporterWorker.export(StackdriverExporterWorker.java:161)
	at io.opencensus.exporter.stats.stackdriver.StackdriverExporterWorker.run(StackdriverExporterWorker.java:209)
	at java.base/java.lang.Thread.run(Thread.java:844)

May 30, 2018 2:35:39 PM io.opencensus.exporter.stats.stackdriver.StackdriverExporterWorker export
WARNING: Exception thrown when exporting TimeSeries.
java.lang.NoSuchMethodError: com.google.common.base.Throwables.throwIfInstanceOf(Ljava/lang/Throwable;Ljava/lang/Class;)V
	at com.google.api.gax.rpc.ApiExceptions.callAndTranslateApiException(ApiExceptions.java:54)
	at com.google.api.gax.rpc.UnaryCallable.call(UnaryCallable.java:112)
	at com.google.cloud.monitoring.v3.MetricServiceClient.createTimeSeries(MetricServiceClient.java:1157)
	at io.opencensus.exporter.stats.stackdriver.StackdriverExporterWorker.export(StackdriverExporterWorker.java:182)
	at io.opencensus.exporter.stats.stackdriver.StackdriverExporterWorker.run(StackdriverExporterWorker.java:209)
	at java.base/java.lang.Thread.run(Thread.java:844)
```

Regardless of the metrics from userland, I believe that we shouldn't have a crash in the exporter

**Comment by songy23** [comment]
This is a known issue due to Guava version conflicts in cloud client library (see https://github.com/census-instrumentation/opencensus-java/issues/1090), though I'm surprised to see this happened again after https://github.com/census-instrumentation/opencensus-java/pull/1095. My guess is there's other dependencies in your pom.xml that shades the Guava version in OpenCensus.

 For now please add an explicitly dependency on Guava v20.0 or above. I would say this is due to a backwards incompatible change in cloud client library, rather than an issue on OpenCensus side.

**Comment by songy23** [comment]
Closing for now - there's really not much we can do about the version conflicts, since we have to continue using Guava 20.0 in OpenCensus (to be consistent with gRPC). Please feel free to reopen if adding direct dependency on Guava doesn't resolve this.

**Comment by songy23** [comment]
Sure, please add the following lines to the dependencies in your pom.xml file:

```
<dependency>
    <groupId>com.google.guava</groupId>
    <artifactId>guava</artifactId>
    <version>25.1-jre</version>
</dependency>
```

If my theory is correct, this should fix the issue. I'll post a PR to mention this in exporter README.

**Comment by songy23** [comment]
OK I think I found the problem... by running `mvn dependency:tree` I saw this:
```bash
[INFO] +- io.grpc:grpc-protobuf:jar:1.10.1:compile
[INFO] |  +- com.google.protobuf:protobuf-java:jar:3.5.1:compile
[INFO] |  +- com.google.guava:guava:jar:19.0:compile
[INFO] |  +- com.google.protobuf:protobuf-java-util:jar:3.5.1:compile
[INFO] |  +- com.google.api.grpc:proto-google-common-protos:jar:1.0.0:compile
[INFO] |  \- io.grpc:grpc-protobuf-lite:jar:1.10.1:compile
```
gRPC-protobuf depends on an outdated Guava version, which doesn't work with the latest cloud client library. So a quicker fix is to update the gRPC version to 1.12.0 (the latest version).

**Comment by odeke-em** [comment]
>Sure, please add the following lines to the dependencies in your pom.xml file:

Great, thank you @songy23! Houston we have touchdown -- it works great now!
<img width="1201" alt="screen shot 2018-05-30 at 3 52 29 pm" src="https://user-images.githubusercontent.com/4898263/40751771-7eb74664-6421-11e8-96dc-bdf7b8b98c39.png">

**Comment by songy23** [comment]
Great!
