### ISSUE TITLE
Consider putting "Metrics" and "SpanData" under one directory "Export"

### ISSUE THREAD

**Issue by songy23** [census-instrumentation/opencensus-java#1239]
Pros:
- `Metrics` and `SpanData` have very similar exporting mechanism.
- Makes it clear that everything under `Export` directory is for exporting.
- Similar layout to `api`, `impl-core` and `impl` (where we have tags, stats and tracing in one artifact).

Cons (from @sebright ):
- `Metrics` and `SpanData` are more descriptive as artifact names.
- There are APIs for reporting pre-aggregated values in `Metrics`.
- Each exporter would only need to depend on one of `Metrics` or `SpanData`.
- It could be confusing to have both export and exporters directories.

**Comment by songy23** [comment]
FYI, the new export service proto put span and metrics together: https://github.com/census-instrumentation/opencensus-proto/pull/60. If this is the standard for other language, Java should probably do the same.

**Comment by adriancole** [comment]
just mentioning that coupling is easy to do and hard to undo. one of the
big attractions of census vs other libraries is that there is clean
separation between tracing and metrics. this allows opt-in vs force-in on
both consumer and service provider side (export). Let's keep this in
foreground.

If we decide to remove the feature of decoupling in either side directly or
indirectly.. let that be a very distinct act which effects messaging and
maybe even the web site.

**Comment by bogdandrutu** [comment]
@adriancole is not about coupling the APIs is about having one artifact for the exporters. The disadvantage is that users will depend on more artifacts. Don't know if that is a problem.

**Comment by adriancole** [comment]
my response was to the comment about the tie-in to the proto change.. sorry
threading didn't work as I expected.

the change as defined here looks mostly like organization. anyway carry on
and thanks.

**Comment by bogdandrutu** [comment]
This is not going to happen right now.
