### ISSUE TITLE
Consider replace ByteArrayOutputStream and access buffer directly in StatsSerializer.serialize()

### ISSUE THREAD

**Issue by songy23** [census-instrumentation/opencensus-java#128]
As @technicalYogi mentioned in PR #124, directly using ByteArrayOutputStream and call toByteArray() may not be very efficient, as it needs to copy memory to different location. Instead he/she suggests inheriting from ByteArrayOutputStream and access the buffer directly. May be worth considering.

**Comment by sebright** [comment]
This change may not be necessary with #213.

**Comment by songy23** [comment]
Agree, going to close this issue since it's outdated.
