### ISSUE TITLE
Should we mention OpenCensus-Java is currently in Beta quality level?

### ISSUE THREAD

**Issue by songy23** [census-instrumentation/opencensus-java#1286]
Definition of [Beta](https://github.com/GoogleCloudPlatform/google-cloud-java#versioning) quality level:

> Beta: Libraries defined at a Beta quality level are expected to be mostly stable and we're working towards their release candidate. We will address issues and requests with a higher priority.

Looks like Beta matches our current quality level. I think the plan is we will officially move to GA level after the v1.0.0 major release.

From discussion: https://github.com/census-instrumentation/opencensus-java/pull/1285#discussion_r198628596.

**Comment by sebright** [comment]
I think that makes sense.
