### ISSUE TITLE
Consider adding an artifact "metrics-exporter-common"

### ISSUE THREAD

**Issue by songy23** [census-instrumentation/opencensus-java#1324]
This artifact will contain utils for all exporters, like [DaemonThreadFactory](https://github.com/census-instrumentation/opencensus-java/blob/master/exporters/stats/stackdriver/src/main/java/io/opencensus/exporter/stats/stackdriver/StackdriverStatsExporter.java#L329-L348).

Original discussion: https://github.com/census-instrumentation/opencensus-java/pull/1320#discussion_r203500049

**Comment by bogdandrutu** [comment]
Probably the namespace (to be consistent with trace/stats):
io.opencensus.exporter.metrics.common

All the stats exporters will be moved later to:
io.opencensus.exporter.metrics.XXX

Does this match with your idea?

**Comment by songy23** [comment]
> Probably the namespace (to be consistent with trace/stats):
io.opencensus.exporter.metrics.common

This makes sense. Will we have another io.opencensus.exporter.trace.common for trace utils like https://github.com/census-instrumentation/opencensus-java/issues/1330?

**Comment by bputt** [comment]
It'd be great if you provided a TLS wrapper which would allow folks to use certs to encrypt the traffic outgoing.

**Comment by songy23** [comment]
Fixed in https://github.com/census-instrumentation/opencensus-java/pull/1647.
