### ISSUE TITLE
Version upgrade

### ISSUE THREAD

**Issue by elharo** [census-instrumentation/opencensus-java#1327]
Please answer these questions before submitting a bug report.

### What version of OpenCensus are you using?

head

Here are some upgrades I noticed this project could use because they cause dependency issues downstream:

 appengineVersion = '1.9.63' . --> 1.9.64
 findBugsVersion = '3.0.2'
 
Less critical but 
    truth: 'com.google.truth:truth:0.30',
     can move to 0.42.0

There are likely some I didn't notice.

**Comment by songy23** [comment]
Thanks for reporting this, I posted a PR to update the dependencies.

It would be nice if we could automate the dependency updates. There are some automation tools for Maven (https://github.com/census-instrumentation/opencensus-java/issues/892), though I don't know if there are similar ones for Gradle.

**Comment by songy23** [comment]
I didn't manage to upgrade the version of `truth` or `findbugs` since they've caused problems to contrib/agent build. Opened https://github.com/census-instrumentation/opencensus-java/issues/1333 to follow up.
