### ISSUE TITLE
Zipkin exporter attributevalue encoding issue

### ISSUE THREAD

**Issue by bputt** [census-instrumentation/opencensus-java#1330]
### What version of OpenCensus are you using?
0.15.0

### What JVM are you using (`java -version`)?
1.8

### What did you do?
If possible, provide a recipe for reproducing the error.
```
Scope scopedTags = tagger.currentBuilder().buildScoped();
Scope ss = tracer.spanBuilder("Spantest.a")
                   .startScopedSpan()) {
                       tracer.getCurrentSpan().putAttribute("my-test-string", AttributeValue.stringAttributeValue("abcd"));
                   }
```

### What did you expect to see?
Zipkin reporting the value as ```abcd```

### What did you see instead?
Zipkin reports the value as ```AttributeValueString(stringValue=abcd)```

![zipkin-trace-screenshot](https://user-images.githubusercontent.com/946047/42975571-c73faa76-8b8a-11e8-969f-0560095e70e1.png)

**Comment by songy23** [comment]
This is related to https://github.com/census-instrumentation/opencensus-java/blob/master/exporters/trace/zipkin/src/main/java/io/opencensus/exporter/trace/zipkin/ZipkinExporterHandler.java#L168-L170:
```java
  private static String attributeValueToString(AttributeValue attributeValue) {
    return attributeValue.toString();
  }
```

I think the string `AttributeValue` is represented this way because there are 3 types of `AttributeValue` (string, boolean and long) and we want to differentiate them when exporting. For example, if we just grad the value of `AttributeValue` when exporting, it would be difficult to differentiate between `AttributeValue.stringAttributeValue("1000")` and `AttributeValue.longAttributeValue("1000")`.

/cc @adriancole  @bogdandrutu

**Comment by bputt** [comment]
Could you utilize the ```match``` function to get its value?

```
public final <T> T match(
    Function<? super String, T> stringFunction,
    Function<? super Boolean, T> booleanFunction,
    Function<? super Long, T> longFunction,
    Function<Object, T> defaultFunction) {
        return stringFunction.apply(getStringValue());
    }
```

**Comment by songy23** [comment]
Yes we can do that, I mean if we just grab the value, it may be difficult to retain the type information on `AttributeValue` (boolean vs. long vs. string), though I'm not sure how important it is to keep this information.

**Comment by bputt** [comment]
Yea, I can't imagine it being too important as its being shipped to zipkin at that point, so you'd only be losing the information at the transport level which isn't needed

**Comment by bogdandrutu** [comment]
I think we should do the match thing. @bputt do you want to write a PR otherwise @songy23  or I can do it.

Thanks for reporting this issue.

**Comment by bputt** [comment]
What do you recommend for java 1.7 and 1.8 support? It seems the match thing only works with 1.8

**Comment by songy23** [comment]
The `match` method is Java 6 compatible:
https://github.com/census-instrumentation/opencensus-java/tree/master/api#opencensus-api

**Comment by bogdandrutu** [comment]
Try something like this:

```
private static Function<String, String> STRING_ATTRIBUTE_FUNCTION =
    new Function<String, String>() {
      @Override
      public String apply(String stringValue) {
        return stringValue;
      }
    };

private static Function<Boolean, String> BOOLEAN_ATTRIBUTE_FUNCTION =
    new Function<Boolean, String>() {
      @Override
      public String apply(Boolean booleanValue) {
        return booleanValue.toString();
      }
    };

private static Function<Long, String> LONG_ATTRIBUTE_FUNCTION =
     new Function<Long, Void>() {
        @Override
        public String apply(Long longValue) {
          return longValue.toString();
        }
     };

private static String attributeValueToString(AttributeValue attributeValue) {
attributeValue.match(
        STRING_ATTRIBUTE_FUNCTION,
        BOOLEAN_ATTRIBUTE_FUNCTION,
        LONG_ATTRIBUTE_FUNCTION,
        Functions.</*@Nullable*/ Void>returnNull());
}
```

**Comment by bogdandrutu** [comment]
@songy23 I also think these classic functions that we need for multiple exporters Attributes to string can be helpers in the exporter-trace-common artifact similar with what we discuss for metrics.

**Comment by falenn** [comment]
For returning A String as a target attribute type on the wire, I've employed this function implementation in the match:
`value.match(String::toString, Object::toString, Object::toString, Object::toString);`

So, whatever type of AttributeValue is created, I get a String back.  Object::toString leverages the java.lang.Object toString method to avoid disambiguity with java.lang.Long and java.lang.Boolean "toString" methods with multiple signatures.

Thoughts on this?
