### ISSUE TITLE
Adding top-level attributes

### ISSUE THREAD

**Issue by bputt** [census-instrumentation/opencensus-java#1331]
Feature request:
It'd be beneficial to set a default set of attributes for the entire trace that would get applied when the spans are built in the exporters.

Let's say the receiving system interacts with an attribute X and each system that sends the trace has to send X with some value. Each system can utilize a default (configured upfront) and or specify a value for X within any span where applicable.

**Comment by songy23** [comment]
Duplicate of https://github.com/census-instrumentation/opencensus-java/issues/1633.
