### ISSUE TITLE
Custom Trace Spans Not Showing in StackDriver

### ISSUE THREAD

**Issue by briantq** [census-instrumentation/opencensus-java#1391]
Please answer these questions before submitting a bug report.

### What version of OpenCensus are you using?
0.15

### What JVM are you using (`java -version`)?
1.8.0_162

### What did you do?
I am trying to incorporate OpenCensus into my Standard Java8 Google App Engine instance.  This is the suggested way to add custom trace information into StackDriver (https://cloud.google.com/trace/docs/setup/java).  

I have followed the instructions to initialize the StackDriver exporter
`StackdriverTraceExporter.createAndRegister(
                    StackdriverTraceConfiguration.builder().setProjectId(projectId).build());`

I then got the Tracer element and have been using it to create and complete spans
`tracer = Tracing.getTracer();
Span span = tracer.spanBuilder(spanName).setSampler(Samplers.alwaysSample()).startSpan()
..some work...
span.end();`

### What did you expect to see?
I expected to see my custom spans displayed in the StackDriver console.

### What did you see instead?
When I do this I am not seeing my custom spans in the StackDriver trace console.  I am seeing the Google App Engine traces (Memcache, Datastore, etc). 

Based on previous conversation, I know there is a flush delay.  GAE is definitely not stopping, but not sure about each request Thread. That being said Google SDK is able to record spans in the same environment, I have also confirmed Trace API is enabled for the project.  I initially did not include the project id (as it was suggested that GAE could handle it based on the environment), but after that didn't work I have tried it with the project id with no change.

**Comment by mayurkale22** [comment]
I tried sample example on GAE with OpenCensus + StackDrive and it worked for me. Please find below sample code. Let us know if you still face the issue. 

https://cloud.google.com/appengine/docs/standard/java/quickstart

```
package com.example.appengine.java8;

// [START example]
import com.google.appengine.api.utils.SystemProperty;
import io.opencensus.common.Scope;
import io.opencensus.exporter.trace.stackdriver.StackdriverTraceConfiguration;
import io.opencensus.exporter.trace.stackdriver.StackdriverTraceExporter;
import io.opencensus.trace.*;
import io.opencensus.trace.config.TraceConfig;
import io.opencensus.trace.samplers.Samplers;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.HashMap;
import java.util.Map;
import java.util.Properties;

import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

// With @WebServlet annotation the webapp/WEB-INF/web.xml is no longer required.
@WebServlet(name = "HelloAppEngine", value = "/hello")
public class HelloAppEngine extends HttpServlet {

  private static final Tracer tracer = Tracing.getTracer();

  static {
    try {
      setupOpenCensusAndStackdriverExporter();
    } catch (IOException e) {
      System.err.println("Failed to create and register OpenCensus Stackdriver Trace exporter "+ e);
    }
  }

  private static String processLine(String line) {
    try (Scope ss = tracer.spanBuilder("processLine").startScopedSpan()) {
      return line.toUpperCase();
    }
  }

  private static void readEvaluateProcessLine(String in) throws IOException {
    try (Scope ss = tracer.spanBuilder("repl").startScopedSpan()) {
      String line = in;

      // Annotate the span to indicate we are invoking processLine next.
      Map<String, AttributeValue> attributes = new HashMap<String, AttributeValue>();
      attributes.put("len", AttributeValue.longAttributeValue(line.length()));
      attributes.put("use", AttributeValue.stringAttributeValue("repl"));
      Span span = tracer.getCurrentSpan();
      span.addAnnotation("Invoking processLine", attributes);

      String processed = processLine(line);
      System.out.println("< " + processed + "\n");
    }
  }

  @Override
  public void doGet(HttpServletRequest request, HttpServletResponse response)
      throws IOException {
    Properties properties = System.getProperties();

    readEvaluateProcessLine("hello APP Engine");

    response.setContentType("text/plain");
    response.getWriter().println("Hello App Engine - Standard using "
            + SystemProperty.version.get() + " Java "
            + properties.get("java.specification.version"));
  }

  public static String getInfo() {
    return "Version: " + System.getProperty("java.version")
          + " OS: " + System.getProperty("os.name")
          + " User: " + System.getProperty("user.name");
  }

  private static void setupOpenCensusAndStackdriverExporter() throws IOException {
    TraceConfig traceConfig = Tracing.getTraceConfig();
    // For demo purposes, lets always sample.
    traceConfig.updateActiveTraceParams(
            traceConfig.getActiveTraceParams().toBuilder().setSampler(Samplers.alwaysSample()).build());

    StackdriverTraceExporter.createAndRegister(
            StackdriverTraceConfiguration.builder()
                    .build());
  }

}
// [END example]
```

![screen shot 2018-08-27 at 6 51 58 pm](https://user-images.githubusercontent.com/6525361/44696023-a5189480-aa2a-11e8-8858-c7ed3fb0e2d8.png)

**Comment by briantq** [comment]
@mayurkale22 Thank you very much for putting together a sample to run!  I took what you had and found that if you run in a single thread this does work.  Unfortunately, my environment is multithreaded (called threadsafe on google app engine).  I believe this spawns a new Thread for each request.  In this environment, the traces are not getting reported, I imagine due to the 5 second flush delay.  

Can I change the name to this issue to denote it as a feature request to allow StackDriver exporter to work in a multi threaded environment?  If not, I definitely don't mind opening another issue to track the feature request.

Thanks again for the help!

**Comment by mayurkale22** [comment]
@briantq I would suggest you to make your thread sleep for sometime (>5 secs) to see the behavior, otherwise open new feature request.

**Comment by briantq** [comment]
@mayurkale22 Thanks for the suggestion but since I am trying to be as performant as possible, making request Threads live 10+ time longer than just to get trace information will cost me much more in extra resources that it's not a viable option.  I will open a feature request.  

Thank you for your help!!
