### ISSUE TITLE
Check return value of Context.attach() in a more meaningful way.

### ISSUE THREAD

**Issue by songy23** [census-instrumentation/opencensus-java#1407]
In gRPC 1.14.0 `Context.attach()` is annotated with `@CheckReturnValue`. As @zhangkun83 mentioned in https://github.com/grpc/grpc-java/issues/4817#issuecomment-418396475, this is intended and we should check the returned value to verify attaching/detaching the context.

Currently we have a work around to pass the `findBugs` check (https://github.com/census-instrumentation/opencensus-java/pull/1404#discussion_r214448178). Consider changing the check in a more meaningful way.

**Comment by zhangkun83** [comment]
To clarify, the returned object of `attach()` needs to be saved and later passed to `detach()` when exiting the scope of the context.

**Comment by songy23** [comment]
Already fixed.
