### ISSUE TITLE
build.gradle: source and target compatibility are for 1.6 but this repo uses 1.7 features 

### ISSUE THREAD

**Issue by odeke-em** [census-instrumentation/opencensus-java#1428]
While reviewing opencensus-proto PR https://github.com/census-instrumentation/opencensus-proto/pull/102 I compared with the build.gradle file in this repository and noticed https://github.com/census-instrumentation/opencensus-java/blob/4ddf824f81d1e4b5ebdfd988ccc140686b9fa3f5/build.gradle#L53-L54

However, try-with-resources was only added in Java 7 https://docs.oracle.com/javase/tutorial/essential/exceptions/tryResourceClose.html
 so perhaps those compatibilities need updates?

**Comment by songy23** [comment]
IIUC the 1.6 compatibility restriction only applies to APIs. In our API we support usage in both JDK1.6 and 1.7+, for example: https://github.com/census-instrumentation/opencensus-java/blob/660e8f375bb483a3eb817940b3aa8534f86da314/api/src/main/java/io/opencensus/trace/Tracer.java#L110-L144.

**Comment by odeke-em** [comment]
Oh I see. I guess my first hit of `grep -Rn 'try (` * in this repository gave a false impression. It only seems like the examples are the ones that use try-with-resources https://github.com/census-instrumentation/opencensus-java/search?p=3&q=try+%28&unscoped_q=try+%28.

In that case I'll close this issue.
