### ISSUE TITLE
Replace mean with sum in the stats Distribution to make it compatible with Metrics.

### ISSUE THREAD

**Issue by mayurkale22** [census-instrumentation/opencensus-java#1544]
We also consider to change ```mean``` -> ```sum``` in stats Distribution to make it compatible with Metrics Distribution.
Same as: https://github.com/census-instrumentation/opencensus-java/pull/1542

**Comment by songy23** [comment]
This should be a very straightforward change, though for current usage I slightly prefer keeping `mean`, since [RpcZ page](https://github.com/census-instrumentation/opencensus-java/tree/master/contrib/zpages#view-rpc-stats-on-rpcz-page) relies on the `mean`/average stats.

**Comment by songy23** [comment]
`AggregationData` and `ViewData` will be deprecated in favor of metric data models.
