### ISSUE TITLE
checker framework annotation OR javax.annotations.Nullable

### ISSUE THREAD

**Issue by mayurkale22** [census-instrumentation/opencensus-java#1588]
Currently, OC Java uses a mix of checker framework annotation (`/*@Nullable*/`) and `@javax.annotations.Nullable` . Things are not consistent everywhere in the library.

**Comment by songy23** [comment]
My suggestion is use `@javax.annotations.Nullable` whenever possible. Only use `/*@Nullable*/` for generics.

**Comment by sebright** [comment]
There is also a note on annotations here: https://github.com/census-instrumentation/opencensus-java/blob/master/CONTRIBUTING.md#checker-framework-null-analysis

**Comment by bogdandrutu** [comment]
Thanks @sebright. Your comment matches with my understanding and what @songy23 proposed. I think we should not use the comment when we can use the annotation. Also we are slowly moving to java7 so the comment can be removed completely.
