### ISSUE TITLE
 Stackdriver/MonitoredResource: decide how to handle "location" label

### ISSUE THREAD

**Issue by mayurkale22** [census-instrumentation/opencensus-java#1593]
For some resources (GCP or AWS instance),  "project_id" and "location" labels are part of the identity. But for the "k8s_container" resource, they primarily indicate where the signal data should be stored.

Pointer: https://github.com/census-instrumentation/opencensus-java/blob/master/exporters/stats/stackdriver/src/main/java/io/opencensus/exporter/stats/stackdriver/StackdriverExportUtils.java#L439

**Comment by songy23** [comment]
I think this is addressed with the updated resource types and labels.
