### ISSUE TITLE
CNFE MonitoredResourceMetadataOrBuilder due to grpc runtime conflict

### ISSUE THREAD

**Issue by clehene** [census-instrumentation/opencensus-java#1635]
Please answer these questions before submitting a bug report.

### What version of OpenCensus are you using?

0.18.0

### What JVM are you using (`java -version`)?

1.8.0_181

### What did you do?
If possible, provide a recipe for reproducing the error.

Running a gRPC server with OpenCensus and StackDrive exporter 

### What did you expect to see?

not see errors

### What did you see instead?

```
Dec 08, 2018 12:42:38 PM io.opencensus.exporter.stats.stackdriver.StackdriverExporterWorker run
WARNING: Exception thrown by the Stackdriver stats exporter.
java.lang.NoClassDefFoundError: com/google/api/MonitoredResourceMetadataOrBuilder
	at io.opencensus.exporter.stats.stackdriver.StackdriverExportUtils.createTimeSeriesList(StackdriverExportUtils.java:255)
	at io.opencensus.exporter.stats.stackdriver.StackdriverExporterWorker.export(StackdriverExporterWorker.java:197)
	at io.opencensus.exporter.stats.stackdriver.StackdriverExporterWorker.run(StackdriverExporterWorker.java:239)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: com.google.api.MonitoredResourceMetadataOrBuilder
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 4 more
```

The problem seems to be due to a conflict 
0.18.0 depends on grpc 1.14.0 but com.google.cloud:google-cloud-trace:jar:0.70.0-beta depends on 1.15
```
 io.opencensus:opencensus-exporter-trace-stackdriver:jar:0.18.0 -> com.google.cloud:google-cloud-trace:jar:0.70.0-beta -> io.grpc:grpc-auth:jar:1.15.0 -> io.grpc:grpc-core:jar:[1.15.0,1.15.0]]
```

**Comment by clehene** [comment]
The conflict is due to 

```
[INFO] +- io.grpc:grpc-protobuf:jar:1.17.0:compile
[INFO] |  +- com.google.protobuf:protobuf-java:jar:3.5.1:compile
[INFO] |  +- com.google.guava:guava:jar:26.0-android:compile
[INFO] |  |  +- org.checkerframework:checker-compat-qual:jar:2.5.2:compile
[INFO] |  |  \- com.google.j2objc:j2objc-annotations:jar:1.1:compile
[INFO] |  +- com.google.api.grpc:proto-google-common-protos:jar:1.0.0:compile
```

It looks like gRPC relies on an old version of common-protos

**Comment by bogdandrutu** [comment]
/cc @zhangkun83 @carl-mastrangelo

The common-protos artifact is almost 1y old and google cloud java clients depend on 1.12.0
https://github.com/googleapis/google-cloud-java/blob/master/google-api-grpc/pom.xml#L128

**Comment by carl-mastrangelo** [comment]
I was under the impression that there is a way in the pom file to pick latest.   (By using a `[` character IIRC. ).  We can look at upgrading the common protos dep, but I think this will happen again in the future.

**Comment by ejona86** [comment]
The only way to "avoid" this with Maven is for users to use maven-enforcer's requireUpperBoundDeps, which will notice the problem and users can either reorder their dependencies or add an explicit dependency on the newer version. Gradle users don't suffer from this problem.

@carl-mastrangelo, the `[]` syntax doesn't really solve this problem, and in general is a bad idea because the version it selects changes as new versions are released. The only real "sane" way to use `[]` is to include only a single version inside, which is what grpc does with Netty. But this means you only support that one version, which is inappropriate in this case.

**Comment by bogdandrutu** [comment]
@clehene I think you can use `requireUpperBoundDeps` in your maven config for the moment. gRPC upgraded their dependencies.
