### ISSUE TITLE
In-memory tracing agent for unit tests

### ISSUE THREAD

**Issue by clehene** [census-instrumentation/opencensus-java#1640]
I'd like to run unit tests with code that has tracing. For this I'd need the traces to go to an in-memory trace receiver.

**Comment by songy23** [comment]
Is this something that you want: https://github.com/census-instrumentation/opencensus-java/blob/master/exporters/trace/ocagent/src/test/java/io/opencensus/exporter/trace/ocagent/FakeOcAgentTraceServiceGrpcImpl.java?

It can be used with an `InProcessServer`: https://github.com/census-instrumentation/opencensus-java/blob/master/exporters/trace/ocagent/src/test/java/io/opencensus/exporter/trace/ocagent/OcAgentTraceServiceRpcHandlersTest.java#L77-L82.

**Comment by songy23** [comment]
Closing but feel free to reopen if you have follow-up questions.
