### ISSUE TITLE
opencensus-contrib-http-servlet missing in Maven Central

### ISSUE THREAD

**Issue by dansiviter** [census-instrumentation/opencensus-java#1643]
### What version of OpenCensus are you using?
0.18.0

### What JVM are you using (`java -version`)?
Any

### What did you do?
If possible, provide a recipe for reproducing the error.
Add `io.opencensus:opencensus-contrib-http-servlet:0.18.0` as a dependency.

### What did you expect to see?
The above resource downloaded from maven central

### What did you see instead?
Dependency doesn't exist and appears to have not been uploaded to Maven Central.

**Comment by bogdandrutu** [comment]
This is cause by this:
https://github.com/census-instrumentation/opencensus-java/blob/master/build.gradle#L386

@rghetia any update when the package will be available?

**Comment by rghetia** [comment]
I'll post the PR today.

**Comment by songy23** [comment]
opencensus-contrib-http-servlet is included in 0.19.0 Release: https://github.com/census-instrumentation/opencensus-java/releases/tag/v0.19.0.

Artifacts will be available on Maven in a minute.
