### ISSUE TITLE
Default max annotation and attribute count should be increased

### ISSUE THREAD

**Issue by sjkaris** [census-instrumentation/opencensus-java#1662]
The current default annotation and attribute max count is 32. These values are too low as a max value, and I propose increasing it to 128.

Relevant file:
https://github.com/census-instrumentation/opencensus-java/blob/02ade038e4c11dece33ad41cfd10dad0953a4f35/api/src/main/java/io/opencensus/trace/config/TraceParams.java#L41

**Comment by songy23** [comment]
Please file an issue under opencensus-specs instead, this needs to be consistent across languages. (https://github.com/census-instrumentation/opencensus-specs/issues)

**Comment by sjkaris** [comment]
https://github.com/census-instrumentation/opencensus-specs/issues/226
