### ISSUE TITLE
Create a scoped span in OcHttpServletListener

### ISSUE THREAD

**Issue by rghetia** [census-instrumentation/opencensus-java#1663]
Please answer these questions before submitting a bug report.
Span created by OcHttpServletListener is detached span. This should be a scoped span. This cannot be in HttpServletHandler as reasons outlined in this [comment](https://github.com/census-instrumentation/opencensus-java/pull/1653#discussion_r248252706)

### What version of OpenCensus are you using?
0.19.0

**Comment by songy23** [comment]
Same comment to https://github.com/census-instrumentation/opencensus-java/issues/1686#issuecomment-472639475.

**Comment by rghetia** [comment]
fixed by #1714
