### ISSUE TITLE
Tags: Support HTTP propagation.

### ISSUE THREAD

**Issue by songy23** [census-instrumentation/opencensus-java#1667]
1. Agree on the text format for tag HTTP propagation.
2. Add HTTP plugin for tags.

**Comment by dinooliva** [comment]
Shouldn't 1 be cross-language (e.g. an issue on opencensus-specs)?

**Comment by songy23** [comment]
The spec issue is https://github.com/census-instrumentation/opencensus-specs/issues/65.

This issue is particularly for tracking the Java implementation.
