### ISSUE TITLE
Release 0.19.0?

### ISSUE THREAD

**Issue by dmichel1** [census-instrumentation/opencensus-java#1676]
Would it be possible to get a new release cut? We are eagerly waiting to test out the datadog exporter and would rather not have to maintain a fork of this repo internally.

Thank you

**Comment by bogdandrutu** [comment]
@dmichel1 we will do that this week.

**Comment by songy23** [comment]
Waiting on one more PR from @rghetia. Will do the release today after that PR is submitted.

**Comment by rghetia** [comment]
@songy23 I merged #1699. you can release it now.

**Comment by songy23** [comment]
V0.19.0 Release: https://github.com/census-instrumentation/opencensus-java/releases/tag/v0.19.0.

Artifacts will be available on Maven in a minute.

**Comment by dmichel1** [comment]
thanks all
