### ISSUE TITLE
Servlet Contrib linked to Jetty

### ISSUE THREAD

**Issue by dansiviter** [census-instrumentation/opencensus-java#1683]
Servlet contrib states 'Jetty' in the title and as a 'compile' dependency. The implementation should be agnostic to the servlet implementation that it's used on.

**Comment by dansiviter** [comment]
FYI, it still says 'Jetty' in the README.

**Comment by rghetia** [comment]
> FYI, it still says 'Jetty' in the README.

Thanks for noticing it. I'll have a PR shortly.
