### ISSUE TITLE
Stats/Stackdriver: add 'aws:' prefix for aws_ec2_instance's region field.

### ISSUE THREAD

**Issue by mayurkale22** [census-instrumentation/opencensus-java#1715]
**Expected format:** ```aws:{region}```, **Current format:** ```{region}```.

This is required to change when we [set resource for MonitoredResource builder](https://github.com/census-instrumentation/opencensus-java/blob/master/exporters/stats/stackdriver/src/main/java/io/opencensus/exporter/stats/stackdriver/StackdriverExportUtils.java#L433-L437) inside stackdriver monitoring exporter in case of aws_ec2_instance resource type.

More Info: https://cloud.google.com/monitoring/api/resources#tag_aws_ec2_instance

Detailed error response:
```
{
  "error": {
    "code": 400,
    "message": "One or more TimeSeries could not be written: Unrecognized region or location.: timeSeries[0]",
    "status": "INVALID_ARGUMENT",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.DebugInfo",
        "detail": "One or more TimeSeries could not be written: No zones found for spatial element us-east-1 extracted from region field.: timeSeries[0]"
      }
    ]
  }
}
```

**Comment by songy23** [comment]
The prefix was there when we initially added EC2 resource: https://github.com/census-instrumentation/opencensus-java/pull/1126/files#diff-d2886f5b11a5e3be7a00a8f5fff5a1f0R466.

Looks like we accidentally removed it.

**Comment by bogdandrutu** [comment]
I think we need to fix this (only in the exporter) because it is specific to SD correct?

**Comment by mayurkale22** [comment]
Yes, correct.

**Comment by dinooliva** [comment]
Can we add a unit test to ensure this doesn't happen again?
