### ISSUE TITLE
io.opencensus.contrib.http.jetty: add JavaDoc alongside release

### ISSUE THREAD

**Issue by odeke-em** [census-instrumentation/opencensus-java#1733]
Am currently working on the documentation for the HTTP Jetty integration and on navigating to
https://www.javadoc.io/doc/io.opencensus/opencensus-contrib-http-jetty-client/0.19.1
I get back
<img width="896" alt="screen shot 2019-02-04 at 1 47 44 am" src="https://user-images.githubusercontent.com/4898263/52198161-2c123a00-281f-11e9-8b06-68e8104b7333.png">

but also there is no listing either on 
<img width="573" alt="screen shot 2019-02-04 at 1 50 22 am" src="https://user-images.githubusercontent.com/4898263/52198207-40eecd80-281f-11e9-9517-153d2fdc0b03.png">

Let's ensure that we publish a release along with the JavaDoc.

**Comment by bogdandrutu** [comment]
We forgot a TODO:
https://github.com/census-instrumentation/opencensus-java/blob/master/build.gradle#L485
