### ISSUE TITLE
Stats: Consider providing a convenient API for recording with SpanContext attachment.

### ISSUE THREAD

**Issue by songy23** [census-instrumentation/opencensus-java#1775]
See the original discussion on https://github.com/census-instrumentation/opencensus-java/pull/1771#discussion_r261005718.

Currently we only support <String, String> as attachments for `Exemplar`s, and `TraceID` and `SpanID` are two separate entries in the attachments. Consider providing a convenient API that takes ~~`SpanContext` directly~~ a more generic interface.

**Comment by bogdandrutu** [comment]
Actually I am suggesting to have a <String, LazyString>

**Comment by songy23** [comment]
Fixed with #1779 and #1791.
