### ISSUE TITLE
Make Jaeger Exporter able to send traces to Jaeger-Agent instances

### ISSUE THREAD

**Issue by MichaHoffmann** [census-instrumentation/opencensus-java#1798]
### What version of OpenCensus are you using?
`0.18.0`

### What JVM are you using (`java -version`)?
```
openjdk version "11" 2018-09-25
OpenJDK Runtime Environment (build 11+28-Debian-3)
OpenJDK 64-Bit Server VM (build 11+28-Debian-3, mixed mode, sharing)
```
### What did you do?
I want the Jaeger exporter to send spans to the Jaeger agent via its UDP endpoint. 

### What did you expect to see?
A way to configure the exporter to send spans to our Jaeger agent instances.

### What did you see instead?
No way to configure that scenario.

### Possible Solution

Currently The exporter can be registered with a `thriftEndpoint` or an `HttpSender` and targets the HTTP endpoint of the Jaeger-Collector. According to Jaeger ( https://www.jaegertracing.io/docs/1.8/architecture/#components ) applications should communicate with the agent instead and although its technically possible to send spans to the collector it is not recommended. 

That situation seems to be easily remedied by changing the `com.uber.jaeger.senders.HttpSender` to any implementation of `com.uber.jaeger.senders.ThriftSender`. Since the `com.uber.jaeger.senders.UDPSender` also extends `ThriftSender` one could decide to talk to the agent without changing any of the actual exporter implementations just by using the more abstract `ThriftSender`. 

If that sounds reasonable i would be willing to submit a PR.

**Comment by songy23** [comment]
Fixed in https://github.com/census-instrumentation/opencensus-java/pull/1799.
