### ISSUE TITLE
0.21.0 release

### ISSUE THREAD

**Issue by songy23** [census-instrumentation/opencensus-java#1857]
A placeholder for the next minor release. Remaining items (feel free to edit or add more):

- [x] Finish up the implementation for Cumulative APIs (https://github.com/census-instrumentation/opencensus-java/pull/1856).
- [ ] ~~Decide whether to drop event when disrupter queue is full (https://github.com/census-instrumentation/opencensus-java/pull/1837).~~
- [x] Investigate the issue with Stackdriver exporter (https://github.com/census-instrumentation/opencensus-java/issues/1841).

/cc @paivagustavo

**Comment by paivagustavo** [comment]
Seems like #1837 is going to take longer than expected because it must be discussed on the opencensus-specs. Can this be delayed to next release? It would help me a lot if the new changes on master get released.

**Comment by bogdandrutu** [comment]
I would suggest that we skip, but with the idea to do a new release sooner that will include that change to not block people that need the non-blocking.

**Comment by songy23** [comment]
SGTM, we'll hold https://github.com/census-instrumentation/opencensus-java/pull/1837 till next release (which waits on the conclusion of https://github.com/census-instrumentation/opencensus-specs/issues/262). Will do a release without that change first.

**Comment by songy23** [comment]
Release is done: https://github.com/census-instrumentation/opencensus-java/releases/tag/v0.21.0.
