### ISSUE TITLE
Split RpcConstants into two files.

### ISSUE THREAD

**Issue by zhangkun83** [census-instrumentation/opencensus-java#188]
gRPC core only uses the MeasurementDescriptors, not the ViewDescriptors. Having all of them in RpcConstants forces JVM to load all related classes when loading RpcConstants, even if they are not used. Android is sensitive to class loading time. We'd better put the ViewDescriptors in a separate file.

**Comment by zhangkun83** [comment]
cc @songy23

**Comment by songy23** [comment]
Needs to remove deprecated RpcConstants.java and RpcConstantsTest.java once no code depends on them.

**Comment by songy23** [comment]
Fixed in https://github.com/census-instrumentation/opencensus-java/pull/389
