### ISSUE TITLE
Http measure to track request count

### ISSUE THREAD

**Issue by iamgr0ot** [census-instrumentation/opencensus-java#1968]
### Is your feature request related to a problem? If so, please describe it.
Java Opencensus contrib library doesn't expose http measure to track client request count. 

### Describe the solution you'd like.
Add a measure to track request count

### Describe alternatives you've considered.
We tried using `HTTP_CLIENT_COMPLETED_COUNT_VIEW` to get the count but the unit is wrong (Has `ms` unit but it should be short)

**Comment by songy23** [comment]
Should be resolved with https://search.maven.org/artifact/io.opencensus/opencensus-contrib-http-util/0.24.0/jar. Feel free to reopen if the problem persists with the new release.
