### ISSUE TITLE
Do you have funtion which can add values to jaeger process?

### ISSUE THREAD

**Issue by zheyiyi** [census-instrumentation/opencensus-java#1974]
I use opencensus to create spans.

span.putAttribute(key,value)-----> jaeger UI's tags
span.annotation---->jaeger UI's logs

My question is that on Jaeger Ui, How to add things into process?

![image](https://user-images.githubusercontent.com/12801407/64202475-3c46d200-ce5f-11e9-84cb-56212e007ef9.png)

**Comment by songy23** [comment]
You can configure `Process` by setting `JaegerExporterConfiguration.builder().setServiceName()`.

See https://github.com/census-instrumentation/opencensus-java/blob/1dc78a87748ed5642ff560ab0ed35c2f1021170d/exporters/trace/jaeger/src/main/java/io/opencensus/exporter/trace/jaeger/JaegerTraceExporter.java#L72 and https://github.com/census-instrumentation/opencensus-java/blob/1dc78a87748ed5642ff560ab0ed35c2f1021170d/exporters/trace/jaeger/src/main/java/io/opencensus/exporter/trace/jaeger/JaegerExporterConfiguration.java#L99-L106

**Comment by songy23** [comment]
Mark as resolved, please feel free to reopen if you have any additional questions.
