### ISSUE TITLE
How to trace asynchronous code?

### ISSUE THREAD

**Issue by eiva** [census-instrumentation/opencensus-java#1978]
Sorry for asking this question here...
Is there a recommended way to trace/measure asynchronous code?
What I mean: I have 1 service and set of workers connected via queue.
First -  (start of parent Span) (start child1 span) validate request and store in queue (end child 1 span).
Second - get task from queue and  (start child2 span) do the job (end child 2 span) and store it in result table (end of parent span). 
So what I really want to see is something like that:
```
[------------------------------]
  [---]
                       [---]
```
But from reading documentation it is not really clear what should I do:
Remote span context expects that this span is started - there is no way to continue remote span without starting it again.
So best what I can get looks more like the following:
```
[---]
                      [---]
```
what is not good but missing trace of "how long it took to process request"...

Will really appreciate any help in a recommended way. (and tell me if I want something strange)...

Thanks

**Comment by songy23** [comment]
Consider using `Link`s: https://opencensus.io/tracing/span/link/. Java API: https://github.com/census-instrumentation/opencensus-java/blob/c943c6c63637cc866e92b90dae0e48dccd488130/api/src/main/java/io/opencensus/trace/SpanBuilder.java#L130.

**Comment by eiva** [comment]
Thanks for the reply. The problem here is that there is no way to create a span in one place and finish it in another.
But still, it somehow working...

**Comment by PMandore** [comment]
@eiva do you have sample code on how you did this? Thanks
