### ISSUE TITLE
HttpServletFilter closes span scope too early for getCurrentSpan to work in implementation

### ISSUE THREAD

**Issue by ecourreges-orange** [census-instrumentation/opencensus-java#1997]
Hello,
@rghetia I saw you [coded it](https://github.com/census-instrumentation/opencensus-java/issues/1663) so you probably have an opinion on that.

I think that the [OcHttpServletFilter](https://github.com/census-instrumentation/opencensus-java/blob/d5ba9ce171bc51c38f167fdce660a2828d1a2a35/contrib/http_servlet/src/main/java/io/opencensus/contrib/http/servlet/OcHttpServletFilter.java#L178)
closes its span Scope too early, so whatever I do in my implementation methods that get called after the filter, I get a BlankSpan from getCurrentSpan(), even though my filter is properly called.

The result is that the span I create is not child of the one created by the OcHttpServletFilter, they are independant, 2 traces are created with 1 span each, instead of 1 trace with 2 spans.
```
      Scope scope = Tracing.getTracer().withSpan(handler.getSpanFromContext(context));
      try {
        chain.doFilter(httpReq, httpResp);
      } finally {
        scope.close();
      }

      if (httpReq.isAsyncStarted()) {
        AsyncContext async = httpReq.getAsyncContext();
        async.addListener(listener, httpReq, httpResp);
      } else {
        OcHttpServletUtil.recordMessageSentEvent(handler, context, httpResp);
        handler.handleEnd(context, httpReq, httpResp, null);
      }
    } else {
```

In my implementation, i am just doing this:
```
Scope scope = Tracing.getTracer().spanBuilder("doWork").startScopedSpan();
```
Which I was hoping it would be in the (sub) scope of the filter.

The solution would be this where the scope ends naturally:
```
      Scope scope = Tracing.getTracer().withSpan(handler.getSpanFromContext(context));
      chain.doFilter(httpReq, httpResp);

      if (httpReq.isAsyncStarted()) {
        AsyncContext async = httpReq.getAsyncContext();
        async.addListener(listener, httpReq, httpResp);
      } else {
        OcHttpServletUtil.recordMessageSentEvent(handler, context, httpResp);
        handler.handleEnd(context, httpReq, httpResp, null);
      }
    } else {
```
or this if you really want to keep the scope.close():
```
      Scope scope = Tracing.getTracer().withSpan(handler.getSpanFromContext(context));
      try {
        chain.doFilter(httpReq, httpResp);

        if (httpReq.isAsyncStarted()) {
          AsyncContext async = httpReq.getAsyncContext();
          async.addListener(listener, httpReq, httpResp);
        } else {
          OcHttpServletUtil.recordMessageSentEvent(handler, context, httpResp);
          handler.handleEnd(context, httpReq, httpResp, null);
        }      

      } finally {
        scope.close();
      }
    } else {
```

Am I wrong? 
If I am wrong, please provide an example code with nested spans where the root span is created by the filter.
Thanks a lot,
Regards.

**Comment by rghetia** [comment]
@ecourreges-orange, you need to use OcHttpServletUtil.withScope(), see the example [here](https://github.com/census-instrumentation/opencensus-java/blob/d5ba9ce171bc51c38f167fdce660a2828d1a2a35/contrib/http_servlet/src/main/java/io/opencensus/contrib/http/servlet/OcHttpServletUtil.java#L63-L68).

**Comment by rghetia** [comment]
@ecourreges-orange, if you agree then I can close the issue.

**Comment by ecourreges-orange** [comment]
Sorry, actually it was working, even without the OcHttpServletUtil.withScope(), my intern made an error...
