### ISSUE TITLE
Only seeing Sent.com.google.api.client.http.HttpRequest.execute as traces on Stackdriver

### ISSUE THREAD

**Issue by biril** [census-instrumentation/opencensus-java#2030]
### What version of OpenCensus are you using?
0.25.0

### What JVM are you using (`java -version`)?
openjdk version "1.8.0_232"
OpenJDK Runtime Environment (build 1.8.0_232-b09)
OpenJDK 64-Bit Server VM (build 25.232-b09, mixed mode)

### What did you do?
I have a number of GRPC services written in Kotlin which are running in a Kubernetes cluster, on Google's GKE.

I've followed various pieces of documentation relevant for setting up Stackdriver trace using OpenCensus (notably https://cloud.google.com/trace/docs/setup/java?hl=en_GB). 

Based on that, I'm building a lib which is a common dependency of my services. The lib depends on

```
api
  io.opencensus:opencensus-api:0.25.0,
  io.opencensus:opencensus-exporter-trace-stackdriver:0.25.0

runtimeOnly
  io.opencensus:opencensus-impl:0.25.0
```

Then the services that depend on that lib also feature a bit of initialization that makes use of given service account, along the lines of

```kotlin
fun initialize(base64SAKeyJson: String) {
    with(Tracing.getTraceConfig()) {
      val traceParams = activeTraceParams.toBuilder()
        .setSampler(Samplers.alwaysSample())
        .build()

      updateActiveTraceParams(traceParams)
    }

    val credentials = getGoogleCredentialsFromBase64SAKeyJson(base64SAKeyJson)
    val configuration = StackdriverTraceConfiguration.builder()
      .setCredentials(credentials)
      .build()

    StackdriverTraceExporter.createAndRegister(configuration)
  }
```

(The relevant service account is correctly configured with the `cloudtrace.agent` role and my service logs indicate no error relevant to tracing)

The problem I'm facing is, every single trace shows up as `Sent.com.google.api.client.http.HttpRequest.execute` which is obviously not as expected. (The traces themselves don't even seem to line up with calls that are made to the cluster.) 

Here's a screenshot of Stackdriver's UI which hopefully better demonstrates the issue:

![image](https://user-images.githubusercontent.com/1710505/77334088-41e10800-6d1c-11ea-9a92-69955b822c55.png)

### What did you expect to see?
Traces that correspond to calls going into the cluster.

### What did you see instead?
Just instances of the `Sent.com.google.api.client.http.HttpRequest.execute` 'trace' which does not correspond to calls going into the cluster.

**Comment by mayurkale22** [comment]
Thanks for reporting this!

- What version of gRPC are you using?
- Was this working for you before OpenCensus `v0.25`?

Just so you know: since gRPC `v1.27.0`, OpenCensus dependency is removed from `grpc-core`. A `grpc-census` artifact now exists to provide interceptor/stream tracer factory that applies OpenCensus stats/tracing features. Users who want census integration need to add `grpc-census` artifact to runtime classpath.

**Comment by biril** [comment]
Hi @mayurkale22. Thanks a lot for your prompt reply.

Our version of GRPC is `1.27.2`. Which judging by what you've mentioned is probably the cause of the issue. (I'm relatively confident our current setup has worked in the past with OpenCensus `0.24.0` alongside GRPC `1.22.2`.)

So I'll give `io.grpc:grpc-census:1.27.2` a go and report back here. 👌

**Comment by biril** [comment]
Okay, so this seems to be working fine now. Thanks very much for your advice.

I still get the odd `Sent.com.google.api.client.http.HttpRequest.execute` which I haven't been able to figure out but it's rare enough that I can can live with.

Feel free to close 👍 .

**Comment by mayurkale22** [comment]
Thanks for the confirmation. Closing this issue now.

> I still get the odd Sent.com.google.api.client.http.HttpRequest.execute which I haven't been able to figure out but it's rare enough that I can can live with.

Feel free to open a separate issue to address this.
