### ISSUE TITLE
Add ability to set Stackdriver display name prefix

### ISSUE THREAD

**Issue by OmerLitov** [census-instrumentation/opencensus-java#2040]
### Is your feature request related to a problem? If so, please describe it.
today the metrics name are too verbose. they either contain "custom.googleapis.com/<additional custom prefix>", or "OpenCensus" (without the ability to add to that prefix).
that makes it harder to use in stackdriver, as the actual metric name is not in the display in the picker.

### Describe the solution you'd like.
I would like to be able to define in the StackdriverStatsConfiguration a display name, and this will be used in CreateMetricDescriptorExporter#CreateMetricDescriptorExporter (or directly in StackdriverExportUtils#getDisplayNamePrefix)

### Describe alternatives you've considered.
none come to mind

**Comment by ulfjack** [comment]
The `StackdriverStatsConfiguration.Builder` class has a `setMetricNamePrefix` method. Is that what you're looking for?

**Comment by OmerLitov** [comment]
it is not what I am looking for, since the metricNamePrefix must be a one of the domains approved, mainly "custom.googleapis.com", which is a bit long.
I want to be able to define just the display name.
for reference, when I don't set a metricNamePrefix, the StackdriverExporter sets the metricNamePrefix to be "custom.googleapis.com", **but** sets "OpenCensus" as the display prefix.
you can see that in CreatMetricDescriptorExporter.java, lines 69-70, where the `domain` and `displayNamePrefix` get different values. from the code there, you can see that the `displayNamePrefix` and `domain` can only have different values if `metricNamePrefix` is empty (which will make them take the default values).

I think it can be beneficial to be able to configure them separately.

**Comment by nilebox** [comment]
It does seem like a gap in the implementation, and should be relatively easy to fix.

@OmerLitov would you be interested in making a PR adding support for a separate displayNamePrefix (with a backward compatible behavior when it's not set)? Note that the OpenCensus has been replaced with OpenTelemetry (https://opentelemetry.io/), so we don't actively work on adding new features to its code.

**Comment by OmerLitov** [comment]
I will make the PR, thanks.
just to confirm, can we have a new release once my PR will be merged?
