### ISSUE TITLE
Performance problem with defining finalizer

### ISSUE THREAD

**Issue by spkrka** [census-instrumentation/opencensus-java#2045]
This issue asked for logging of spans that were GC:ed without being closed first.
https://github.com/census-instrumentation/opencensus-java/issues/1876
And this PR implemented support for that by using finalizers:
https://github.com/census-instrumentation/opencensus-java/pull/1877

I made the following simple PR to revert that behaviour, but it does not seem like it will be merged:
https://github.com/census-instrumentation/opencensus-java/pull/2043

The reason for wanting to revert this behavior is that we saw significant performance problems that could be traced back to a large increase of finalization code in GC and also creation of opencensus spans - there is a static synchronization object that is used for that.

Avoiding finalizers is a well established practice - see Effective Java. It's also mentioned in the Checkstyle rule that was disabled: https://checkstyle.sourceforge.io/apidocs/com/puppycrawl/tools/checkstyle/checks/coding/NoFinalizerCheck.html

So instead of going directly for a PR, perhaps it would be better to start a discussion as an issue instead.
Let's try to align on a good solution before making the code changes.

An alternative solution to simply removing the finalization could be to split the class into a base class and two subclasses, where only only of the subclasses overrides finalize and then make the behaviour configurable.
Either you would want to avoid finalizers for performance reasons or you would want to enable finalizers to get logging of misuse of spans. You could even have a mix of it - use sampling to only apply finalizers to a small subset of spans. If there's a systematic problem of not closing spans it would show up anyway.

We could even take it a step further - We could start by not using finalizers but instead keep an atomic counter of currently open spans. If that is continously growing that would be an indicator that we are leaking spans and then we should enable finalizers to assist identifying the problem.

**Comment by nilebox** [comment]
Hey @spkrka, thanks for providing details about the issue you're facing due to usage of finalizer in the OpenCensus code.
While #2046 seems to be a workable solution, it is more complicated that we'd prefer since OpenCensus is now in maintenance mode as you may know.

Given the severity of the issue you're having, and the purpose of the finalizer being purely informative (detection and logging of a common bug), I think we would agree to revert the change and merge your PR #2043.
Does that sound good for you?

**Comment by spkrka** [comment]
Yes, I think #2043 would be great to merge!

**Comment by nilebox** [comment]
Thanks for your patience @spkrka. The fix has been merged, we will try to make a new release within the next few days.

**Comment by spkrka** [comment]
Great, thanks!
