### ISSUE TITLE
TagValue API

### ISSUE THREAD

**Issue by carl-mastrangelo** [census-instrumentation/opencensus-java#29]
Looking through the TagValue class I see some possible performance problems.

First., the TagValue constructor is public,  which means it isn't possible to control access to it.  This is Item #1 in Effective Java.  Any sort of interesting caching behavior will not be possible.

Second, it delegates to `StringUtil.sanitize`.  This method is expensive to call and will hurt performance when being called rapidly.  It will create a lot of garbage by rebuilding the String character by character.  Users of this will not be able to skip this expensive setup every time.  gRPC for example, already limits the possible characters in a lot of places and doesn't need this extra validation.

Third, it doesn't check for Null values.  Are null values allowed?  It seems like it will fail when doing equals or hashCode, but isn't clear that any other part of TagValue will break.  Without any javadoc on the constructor, how will users know what values are valid?

**Comment by dinooliva** [comment]
We've changed the TagKey and TagValue class to provide static factory methods and made the constructors private.  We have also added javadoc to the factory methods explaining the restrictions on the input.

For inputs that match the restrictions on keys/values, no allocations should be necessary and performance should be reasonable.

Null values are not allowed - we have followed the convention of annotating parameter and return types with @Nullable.

**Comment by sebright** [comment]
@carl-mastrangelo The tag factory methods now throw IllegalArgumentException when the argument is invalid and never create new strings.  Do you think that it is also important for the library to provide a way to create a tag key or value without validation, for performance?

**Comment by carl-mastrangelo** [comment]
@sebright Yes!  Tags get created for every RPC presently and it hurts latency.  In gRPC we internally cache such results on some objects to avoid this problem.  (Like MethodDescriptor)

**Comment by sebright** [comment]
I created a new issue for skipping tag validation: #583.  I'll close this issue, since everything else has been addressed.
