### ISSUE TITLE
Leading / Trailing whitespace in StringUtil

### ISSUE THREAD

**Issue by carl-mastrangelo** [census-instrumentation/opencensus-java#31]
StringUtil.sanitize appears to try to clean up input strings, but often leading and trailing whitespace should be removed.  This is especially true for code that is going to go into HTTP headers.

**Comment by dinooliva** [comment]
The StringUtil class is provided primarily to sanitize Census tag keys and values, where the restrictions are on the string lengths and that printable characters.

For now, leading/trailing whitespaces are legal tag keys and values but we are open to reconsidering this - thoughts anyone?

**Comment by sebright** [comment]
I discussed this with @dinooliva, @songy23, @bogdandrutu, and others, and we decided to allow leading or trailing whitespace.
