### ISSUE TITLE
Run Checker Framework null analysis as part of the Gradle build.

### ISSUE THREAD

**Issue by sebright** [census-instrumentation/opencensus-java#359]
See https://checkerframework.org/manual/#nullness-checker.  Null analysis would help detect bugs and also check the Nullable annotations that are part of the API.  There are instructions for using Gradle: https://checkerframework.org/manual/#gradle

**Comment by g-easy** [comment]
I tried using this plugin: https://plugins.gradle.org/plugin/com.jaredsburrows.checkerframework
But it doesn't seem to play well with errorprone.

https://github.com/g-easy/opencensus-java/commit/105176f0730d3bae727a514fbbf104a7cc20c36b

I also start getting errors about "cannot find symbol AutoValue_*"

**Comment by sebright** [comment]
Thanks for trying it out!  Maybe we can run Error Prone and the Checker Framework in separate build jobs, if they don't interact well.  The errors refer to classes generated by the AutoValue annotation processor, so it's possible that the plugin is overriding the list of annotation processors.

**Comment by sebright** [comment]
This question looks like it might be related: https://groups.google.com/forum/#!topic/checker-framework-discuss/e5nt83iAIqo

**Comment by sebright** [comment]
We may need to use stub files to add annotations for other libraries (https://checkerframework.org/releases/0.9.9/checkers-manual.html#stub-creating-and-using).  For example, we could specify that Preconditions.checkNotNull only returns normally when its argument is non-null.
