### ISSUE TITLE
Avoid sharing Java packages between API and implementation libraries.

### ISSUE THREAD

**Issue by sebright** [census-instrumentation/opencensus-java#379]
Using different packages for implementation classes will make it easier to avoid accessing non-public elements in the API library and help maintain backwards compatibility.

**Comment by sebright** [comment]
#483 moved all `tags` implementation classes into the package `io.opencensus.impl.tags` to separate them from the API.  Do you think there is any advantage to also separating the classes from the three implementation libraries, so that we have something like this?

```
opencensus-api:       io.opencensus.tags
opencensus-impl-core: io.opencensus.core.tags
opencensus-impl:      io.opencensus.impl.tags
opencensus-impl-lite: io.opencensus.impl.tags
```
or

```
opencensus-api:       io.opencensus.tags
opencensus-impl-core: io.opencensus.implcore.tags
opencensus-impl:      io.opencensus.impl.tags
opencensus-impl-lite: io.opencensus.impllite.tags
```

**Comment by bogdandrutu** [comment]
I don't think that is needed (separation between packages, the implementation packages are not intended to be shared with other non-internal implementations).

**Comment by sebright** [comment]
My second suggestion was related to https://github.com/census-instrumentation/opencensus-java/pull/343#discussion_r120812070.
