### ISSUE TITLE
Would a Zipkin contrib module be interesting?

### ISSUE THREAD

**Issue by adriancole** [census-instrumentation/opencensus-java#428]
I've had some informal interest in a Zipkin support for this. Such would make it easy to test, as Zipkin can even run as a junit rule. Also, it could help with sites who already run Zipkin (as traces could enter the same depot). Finally, it could help familiarize folks with this project.

Such an integration would likely be an exporter and possibly a pluggable means to control (or append) trace identifiers in B3 format. The latter could be helpful as existing gRPC integration is done via B3 headers. Zipkin support should plug-in nicely to existing hooks in this project.

Generally speaking, I don't work until users are interested in it. If you are interested in this, please click thumbsup or otherwise note how it would be helpful to you. If you think this shouldn't be here, or shouldn't exist at all, you can also mention this.

**Comment by bogdandrutu** [comment]
I think it would be great to have Zipkin as one of the exporting options.
