### ISSUE TITLE
[question] opentracing ?

### ISSUE THREAD

**Issue by jorgheymans** [census-instrumentation/opencensus-java#482]
Apologies for posting this as an issue here but i didn't find other means. I am wondering how opencensus will relate (if at all) to the opentracing api specification (https://github.com/opentracing/specification/blob/master/specification.md) ?

**Comment by mtwo** [comment]
They're different in scope and goals. Census is composed of a [context propagation format](https://github.com/TraceContext), a single distribution of language-specific libraries that include instrumentation hooks for popular web / RPC frameworks and metrics + trace exporters for various backends, and an optional agent that you can run locally to view metrics and RPC stats.

**Comment by jorgheymans** [comment]
OT brands itself as "Consistent, expressive, vendor-neutral APIs for
distributed tracing and context propagation." To the uninitiated outsider
there seems to be quite a bit of overlap in goals hence my question.

Op ma 31 jul. 2017 16:14 schreef Morgan McLean <notifications@github.com>:

**Comment by mtwo** [comment]
OpenTracing provides a standardized API for code to interact with traces, spans, and context. Census provides language-specific libraries that collect traces and metrics from popular web frameworks, display them locally, and submit them to your backend system (Zipkin, Prometheus, etc.). Census also relies on a standard context propagation wire format, rather than having vendors supply one.

**Comment by tsloughter** [comment]
To make sure I understand, since this was confusing to me at first as well, @mtwo you are saying that Census overlaps with OT on "libraries that collect traces .. and submit them to your backend" (both OT libraries like `opentracing-go` and Census libraries interact with traces, spans, contexts) but additionally collects metrics and has a standard context propagation wire format?

**Comment by mtwo** [comment]
Specifically in terms of providing an API for working with traces and spans, there's definitely some overlap between the API that the Census libraries include and OT. As for the differences, in addition to metrics and a standardized context format, the biggest difference is the fact that the Census project publishes a standard library for each language. This is in contrast to OpenTracing and Zipkin, where most of the instrumentation and submission code is located across various different repositories.

**Comment by tsloughter** [comment]
Well, for Erlang users we know "publishes a standard library for each language" never includes us ;). So for me the API differences are what matters.

**Comment by mtwo** [comment]
Shoot, that's right, I'm now connecting this thread to our email conversations! Anyways, the APIs are quite similar and you're correct that they represent a point of overlap between the two projects

**Comment by tsloughter** [comment]
Oh, hah, I didn't realize it was you either :). I just happened to see the issue and was curious to learn more.

**Comment by adriancole** [comment]
At some point there will be a better comparison, but here are some
highlights:

* OpenTracing encourages use of the tracing api for tracing, logging, input
to metrics, and span propagation. Census has separate apis for these
features, so is less decoupled. For example, its metrics api or tracing (or
other apis) can use propagated tags (baggage) without direct dependencies
on eachother. Also, non-request metrics are more natural to record with a
metrics api. None of this means dimensional or timing fidelity is lost,
rather just more flexibility.
* OpenTracing has no tests to show that it works from an end to end
perspective. It is common to find some decisions made ahead of practice,
and these decisions are hard to undo (I can cite a lot of this if you
want). Census packages an implementation with its apis which means the
whole kit is tested. It is also further tested via gRPC directly.
* On a similar note, OpenTracing leaves implementation as an exercise to
the "tracer", which seems to imply more choice, but it has problems. For
example, it is completely fine to drop data, it is unknown how things like
sampling will apply, if at all. Census does plug-in via exporters, which
simplifies and insures an interop contract.
* The census api in my opinion is a better design. For example, it doesn't
encourage leaky practice like ActiveSpan does in open tracing. It places
controls and contracts in the implementation, which prevent abuse such as
using a Span as a logging api

There's a bunch more, but at the end of the day, I'm very happy census
exists as it is a way to have an interoperable kit with less distractions.

On Mon, Aug 14, 2017 at 7:19 AM, Tristan Sloughter <notifications@github.com

**Comment by sebright** [comment]
I think the question has been answered, but please reopen this issue if there is more to discuss.

**Comment by mvpmvh** [comment]
I'm just getting started learning about application performance monitoring in general. Naturally, in my googling, I've stumbled across _both_  [opentracing](http://opentracing.io/) and [opencensus](http://opencensus.io/); and really could not discern the key differences. Even after viewing these links (the opencensus docs are less than ideal) and the above paragraphs, I still have this fundamental question:

When/why would I choose OC over OT/vice versa?

I did find an [uber blog](https://medium.com/opentracing/take-opentracing-for-a-hotrod-ride-f6e3141f7941) which I think details an implementation of OT specs. In what ways is OC comparable to that? Are there tools/blogs/tutorials that showcase the same/similar features?

Like I said: I'm new to this entire thing.

**Comment by adriancole** [comment]
@mvpmvh question which can help others answer. Why would you use either? Are you planning to write custom telemetry code? If so, are you trying to correlate metrics with tracing and logging, or are you trying to update a histogram, or are you trying to create a custom span because there's no framework support for what you want. Describing why you are interesting in writing telemetry code could possibly help answer which api tool chain could be an advantage

**Comment by vgarmash** [comment]
@adriancole seems like you guys looking at OC and OT from the point of writing new application, were you is a software designer and you have 2 options to choose from.
Although at the moment I know many open source libraries and applications, which are being used by us as a software designers and those libraries already instrumented with OT. Many APM and Tracing tools already support storage and visualization of OT data, but only a few support OC. So if I decide to instrument my code with OC, then my tools could be incompatible. If I switch to compatible tool, if could not have support of OT... Therefore my decision of what library to choose, will be motivated not by cleanliness and coolness of API, but by compatibility factor.

So if you want everyone to fall in love with OC, then you need to ask Google Marketing Department to promote it to all APM vendors as a superior option over OT. Once OC is supported by all major APM and Tracing platforms, it would be more natural for library designers and then to software developers to choose OC over OT.

**Comment by adriancole** [comment]
Fyi I am not going to be replying to the last conjecture

**Comment by nmiculinic** [comment]
Does opentracing backend exist for opencensus? This would make this two open standards interoperable on the code level, and it's on system designer the decision which system shall push messages to the final backend (jaeger/stackdriver/...). 

As far as I could research, open tracing has better support for some backends/languages and vice versa.

**Comment by adriancole** [comment]
I've tried this before and was blocked on this issue as was Felix prior to
me. https://github.com/opentracing/specification/issues/81

It isn't currently possible to create an after-the-fact exporter to the
opentracing library meanwhile. That said, possibly only a couple things in
opentracing namely lightstep don't already have census integration.

**Comment by songy23** [comment]
See https://medium.com/opentracing/a-roadmap-to-convergence-b074e5815289.
