### ISSUE TITLE
Set a default value for ContextUtils.CONTEXT_SPAN_KEY.

### ISSUE THREAD

**Issue by sebright** [census-instrumentation/opencensus-java#534]
CONTEXT_SPAN_KEY.get() should return a default span when the current span isn't set.

https://github.com/census-instrumentation/opencensus-java/blob/1b3a5d60a50914f9574f4dd12a7dd7a187e932d1/api/src/main/java/io/opencensus/trace/unsafe/ContextUtils.java#L30

#533 made the corresponding change for tagging.

**Comment by bogdandrutu** [comment]
This is a bit too late, it will become a backwards incompatible change. I think we should survive without this.
