### ISSUE TITLE
Consider renaming TagContexts class.

### ISSUE THREAD

**Issue by sebright** [census-instrumentation/opencensus-java#588]
It is a little confusing to have both `TagContext` and `TagContexts`, especially since `TagContexts` isn't a utility class.  I can't think of a perfect name for the class, so I figured I would open an issue for discussion.  Here are some ideas:

`Tagger`
`TagContextFactory`
`TagContextManager`
`TagContexts` (current name)

The purpose of the class is to allow creating and manipulating `TagContext`s for implicit and explicit tag propagation.

See https://github.com/census-instrumentation/opencensus-java/pull/498#pullrequestreview-55777822.

**Comment by bogdandrutu** [comment]
+1 for Tagger
