### ISSUE TITLE
Change gRPC to use the newly released tags/stats APIs

### ISSUE THREAD

**Issue by bogdandrutu** [census-instrumentation/opencensus-java#601]
After we release the new APIs we must change gRPC to use them.

**Comment by sebright** [comment]
I removed the milestone, since we need to do this after the APIs have been released.

**Comment by bogdandrutu** [comment]
We should probably create a milestone for gRPC integration. And link all the issues related to gRPC with that.

**Comment by sebright** [comment]
I added a new milestone: https://github.com/census-instrumentation/opencensus-java/milestone/9

**Comment by sebright** [comment]
PR to update gRPC: https://github.com/grpc/grpc-java/pull/3647

**Comment by sebright** [comment]
The PR was merged.
