### ISSUE TITLE
Decide what type of exception to throw when TagContext deserialization fails.

### ISSUE THREAD

**Issue by sebright** [census-instrumentation/opencensus-java#604]
The TagContext deserialization method needs to indicate failure when there is a parse error.  It shouldn't throw an unchecked exception, since the input could be coming from an untrusted source.  The method currently throws an IOException, but after #213/#603, it will no longer need to do IO.

Here are some options:

1. Throw ParseException.  This is what has been released in tracing: https://github.com/census-instrumentation/opencensus-java/blob/master/api/src/main/java/io/opencensus/trace/propagation/BinaryFormat.java#L84  However, it might not be a perfect fit for this case.  See https://github.com/census-instrumentation/opencensus-java/pull/208#issuecomment-294085122
2. Throw a new type of checked exception, such as `TagContextParseException` or a more general type that can be used for both tracing and tagging.  `SpanContext` serialization might also need to be updated to use a custom exception type.  It might be difficult to migrate, though.
3. Return null.  I don't think this is a good option, since it doesn't give any extra information about the error, and users could easily get NullPointerExceptions.

**Comment by adriancole** [comment]
I'm a bit more in favor of an object with error status rather than allocating an exception. It is quite common for traces to be malformed, and usually the corrective action is to restart a trace. Even without error status, you could have an object with partial info, for example, sampling status that was parsed even if trace IDs werent

**Comment by adriancole** [comment]
here are some notes about broken instrumentation which might be neat background https://github.com/openzipkin/b3-propagation/issues/3

**Comment by sebright** [comment]
> I'm a bit more in favor of an object with error status rather than allocating an exception.

That is another option.  We could have something like a StatusOr class (https://github.com/google/protobuf/blob/master/src/google/protobuf/stubs/statusor.h), for efficiency, if errors are common.

> It is quite common for traces to be malformed, and usually the corrective action is to restart a trace. Even without error status, you could have an object with partial info, for example, sampling status that was parsed even if trace IDs werent

> here are some notes about broken instrumentation which might be neat background openzipkin/b3-propagation#3

Thanks for the link!  It looks like it is easier to parse just a SpanId or just a TraceId in that case, since they are separate headers.  For TagContext, it is possible that individual tags are invalid or that nothing can be parsed.  Maybe we should return a result that contains an optional TagContext and an optional error enum, where the error can indicate multiple possibilities.  Here are some example results:

Error             |  TagContext
-----------------|---------------------
no error        | complete TagContext
parse error   | no TagContext
n invalid tags | TagContext containing the valid tags
truncated input | TagContext containing the tags that could be parsed

**Comment by sebright** [comment]
There is more discussion of this issue in https://github.com/census-instrumentation/opencensus-java/pull/603#discussion_r138428013.

**Comment by sebright** [comment]
#621 and #642 added custom checked exceptions for TagContext and SpanContext deserialization.

**Comment by sebright** [comment]
I'm going to close this issue for now, since we added custom checked exceptions.
