### ISSUE TITLE
Decide if we need EmptyTagContext to be public.

### ISSUE THREAD

**Issue by bogdandrutu** [census-instrumentation/opencensus-java#607]
Do you want to have a part of the code where you want to have EmptyTagContext? We do need that for tracing and probably we need something like that for Tags. This question is mostly to understand why EmptyTagContext is private.

**Comment by sebright** [comment]
I don't think the class should be exposed.  EmptyTagContext is supposed to behave the same as an empty instance of the TagContext implementation class, though it needs to be in the API library which can't access the implementation.  The only thing that matters is that the iterator is empty.

Why do you think we should expose it?  Is it to avoid the possibility that we release the library with EmptyTagContext hidden and then realize later that the implementation needs to access it?

**Comment by adriancole** [comment]
In brave we have an isNoop() flag which can avoid the need to check types
at the cost of a method. (Assuming this is what we are interested in)

**Comment by sebright** [comment]
EmptyTagContext is the default TagContext in the gRPC Context, so it should be treated as empty, but not no-op.  I opened an issue for checking whether the implementation is no-op: #585

**Comment by bogdandrutu** [comment]
@sebright my reason is that you MAY want to execute some background operations (work) with not tags:
try(Scope s = TagsContext.withTags(emptyTagContexT)) {
  ... my work
}

Don't know if this is common or not.

**Comment by sebright** [comment]
We already have TagContexts.empty(), so I don't think it's necessary to expose a new class.  If no implementation is available, then empty() returns an instance of NoopTagContext.  (We should probably combine NoopTagContext and EmptyTagContext into the same class, since they have the same implementation.)

**Comment by bogdandrutu** [comment]
That makes a lot of sense. I have BlankSpan which is used as NoopSpan and also as EmptySpan. I don't think it should be any difference. if a need of isNoop that should be at the high level like Tagger or TagsComponents (probably TagsComponents). Users of the TagContext dont need to know if that is a no-op.

**Comment by sebright** [comment]
> Users of the TagContext dont need to know if that is a no-op.

Yes, there is no difference in behavior between empty and no-op TagContexts, because TagContext is immutable.

**Comment by sebright** [comment]
Should we keep EmptyTagContext private?

**Comment by bogdandrutu** [comment]
Yes keep it private for the moment. we can always expose more API but it is harder to delete.
