### ISSUE TITLE
Consider overwriting existing Measure values with MeasureMap.Builder.set.

### ISSUE THREAD

**Issue by sebright** [census-instrumentation/opencensus-java#628]
Currently, `MeasureMap.Builder.set(MeasureDouble, double)` has no effect when the Measure was already set: https://github.com/census-instrumentation/opencensus-java/blob/c82910ac0b04ceba7396887b6e044cf878a46f31/core/src/main/java/io/opencensus/stats/MeasureMap.java#L63

Should we change the behavior to be more similar to `Map.put` and `TagContext.set`, which overwrite previous values?

**Comment by songy23** [comment]
I'm not 100% sure about overwriting existing values. Consider a case when user gets stats of the same Measure from multiple sources, and they want to record them in one MeasureMap:
`Measure measure = ...
MeasureMap.Builder builder = ...
double value1 = .... // from source 1
builder.set(measure, value1);
double value2 = ... // from source2
builder.set(measure, value2)`
As the result both value1 and value2 will be recorded. Again, I'm not sure if this is a valid use case, or we should expect that users should set values for each measure only once.

**Comment by sebright** [comment]
I agree.  Allowing multiple values to be set at once would be more convenient for users, and less surprising.  The only benefit of disallowing multiple values that I can think of is that it might allow us to make optimizations that depend on the uniqueness of measures in the MeasureMap.

**Comment by songy23** [comment]
Fixed in #636
