### ISSUE TITLE
Should we move the current context logic from the API to the implementation library?

### ISSUE THREAD

**Issue by sebright** [census-instrumentation/opencensus-java#632]
While implementing #608, I found that it was difficult to work with the split in the tagging logic between the API and implementation libraries.  The API library contains the gRPC context keys and all of the code for interacting with the current context.  However, the implementation needs to support dynamically enabling and disabling tagging, and we may want to optimize the case where tagging is disabled by not setting or getting the current context.  It would be nice if that logic could be contained completely within the implementation so that we could change it without any backwards compatibility issues.

Should we move all current context logic into the implementation, except for the gRPC context keys?  This would mean making methods like `TagContexts.getCurrentTagContext()` and `TagContexts.withTagContext(TagContext)` abstract.  The downside is that implementations would need to use `io.opencensus.tags.unsafe.ContextUtils` to manipulate the context themselves.  They would also be free to use a completely different implementation of context propagation, but that would be inconsistent with the gRPC Context key that is exposed in `ContextUtils`.

I think that the same issue applies to tracing, if there is no need to propagate the span when tracing is disabled.

/cc @bogdandrutu @dinooliva @songy23

**Comment by bogdandrutu** [comment]
Just making these functions abstract is not a problem, but to make our library work with other context implementation is very hard because context needs also to be propagated between threads, in runnables, callables, executors, etc and we relay on grpc::Context API to help users to do that.

In order for us to allow people to propagate the context in their binary without depending on a certain implementation like grpc::Context (or more exactly without claiming that we work only with that context) means we have to define our own Context API which will mean redefining the grpc::Context API + implementation.

I think the cost of these functions that you mentioned is very small so we can have them be real implementation in the NO-OP and when the library is disabled.

**Comment by sebright** [comment]
> Just making these functions abstract is not a problem, but to make our library work with other context implementation is very hard because context needs also to be propagated between threads, in runnables, callables, executors, etc and we relay on grpc::Context API to help users to do that.
> 
> In order for us to allow people to propagate the context in their binary without depending on a certain implementation like grpc::Context (or more exactly without claiming that we work only with that context) means we have to define our own Context API which will mean redefining the grpc::Context API + implementation.

I wasn't suggesting trying to make the API work with other methods of context propagation.  I only meant that it might be confusing if we left the current context methods abstract but specified that they be implemented using `io.opencensus.tags.unsafe.ContextUtils.EMPTY_TAG_CONTEXT`.

> I think the cost of these functions that you mentioned is very small so we can have them be real implementation in the NO-OP and when the library is disabled.

I'm still a little nervous about putting that assumption into the API.  If we later found that the context operations were slow, we would need to wait for a deprecation cycle before changing it.

We could keep the current context logic in the API and allow the implementation to control whether or not to access the context by adding hooks (e.g., something like `protected abstract boolean shouldAccessContext()`).  The only problem is that it would complicate the API.

**Comment by sebright** [comment]
I'll write a PR to make the current context methods abstract, so that the implementation will have maximum flexibility.

**Comment by bogdandrutu** [comment]
Sure. Maybe try to do the same thing for trace package as well.

I see a problem in testing then because users always have to test with our implementation or provide an implementation/mock of these functions as well.

You may have to really do a good testing package then.

**Comment by sebright** [comment]
I made a PR: #643 

> I see a problem in testing then because users always have to test with our implementation or provide an implementation/mock of these functions as well.
> 
> You may have to really do a good testing package then.

Yes, I'll open an issue for adding a test class if we make the methods abstract.

**Comment by sebright** [comment]
@bogdandrutu I think that users will need to either use a testing library or the real implementation to test what tags are set.  If they run tests with just the API library, then it will ignore any tags that they add to the TagContext.

**Comment by adriancole** [comment]
As we make thinga pluggable we might want some tests to ensure things are
reliable. I recently started making some for brave and could help make them
here if we define what they should do.

https://github.com/openzipkin/brave/blob/master/brave-tests/src/main/java/brave/propagation/CurrentTraceContextTest.java
