### ISSUE TITLE
Simplify Sampler interface

### ISSUE THREAD

**Issue by bogdandrutu** [census-instrumentation/opencensus-java#656]
Move the logic when a Sampler is called in the implementation and change the Sampler interface to apply only on the current Span (ignore things like parent, parent-links, etc.)

1) Move the logic when one sampler is called in the SpanBuilderImpl.
2) Remove parent, hasRemoteParent and parentLinks from the sampler interface.

**Comment by songy23** [comment]
This is already fixed.
