### ISSUE TITLE
Add getState, setState, and isImplementationAvailable methods to the Tracing class.

### ISSUE THREAD

**Issue by sebright** [census-instrumentation/opencensus-java#673]
#659 made a similar change to the Tags class.  This issue is part of #608.

**Comment by adriancole** [comment]
Similar comment to elsewhere. I prefer simple boolean isActive/Enabled/Noop
or similar flag vs state query. Code is quicker and the nuance hasnt proven
terribly interesting in other projects I have worked on. A general Noop
impl convention can address the isImplementationAvailable nuance

All that said, I can live with this

**Comment by adriancole** [comment]
Ps even if we dont expose a Noop type we can always use a noop instance
instead. Ex those wanting to know if there is no implementation can check
tagger == Tagger.NOOP tracer == Tracer.NOOP etc

**Comment by sebright** [comment]
I removed `Tags.isImplementationAvailable` from #659, so no package contains an `isImplementationAvailable` method yet.

**Comment by sebright** [comment]
Since we are deprecating the methods for setting state for stats and tagging (https://github.com/census-instrumentation/opencensus-java/issues/608#issuecomment-342627357), I think we should wait to implement `setState` for tracing until it is needed.

**Comment by sebright** [comment]
Closing, since we need to decide whether to support enabling/disabling functionality at runtime, and that is already handled by #608.
