### ISSUE TITLE
Add no-op RunningSpanStore and SampledSpanStore.

### ISSUE THREAD

**Issue by sebright** [census-instrumentation/opencensus-java#679]
Returning no-op implementations would be more consistent with the stats package, which has a no-op ViewManager.  See https://github.com/census-instrumentation/opencensus-java/pull/677#pullrequestreview-65406615.

**Comment by sebright** [comment]
This change would involve updating the [NoopExportComponent](https://github.com/census-instrumentation/opencensus-java/blob/f8e33e302547d209290611d00ea17b922c225375/api/src/main/java/io/opencensus/trace/export/ExportComponent.java#L68) to return no-op implementations for the two span stores instead of null.

**Comment by HailongWen** [comment]
I made a PR: #824

**Comment by HailongWen** [comment]
Abandon #824 due to incorrect merge history. Added a new PR: #826 .

**Comment by HailongWen** [comment]
Closed by #826.
