### ISSUE TITLE
Consider adding a description field for TagKey

### ISSUE THREAD

**Issue by songy23** [census-instrumentation/opencensus-java#683]
See https://cloud.google.com/monitoring/api/ref_v3/rest/v3/LabelDescriptor

**Comment by sebright** [comment]
How would the description field interact with tag propagation between processes?

**Comment by songy23** [comment]
This field doesn't need to be propagated, it's only needed when we define and export a `TagKey`. Alternatively we can use an internal class (or even a map) that associates a description with a `TagKey`.

Without this field, we can only use hard-coded descriptions when exporting `TagKey`s.

**Comment by sebright** [comment]
How would users add keys to the map?  Would we need to add a method to ViewManager that associates a TagKey with a description?

Another idea is to add a class that contains a TagKey and a description, say ViewTagKey, and then change the `columns` field in View from type `List<TagKey>` to `List<ViewTagKey>`.  Then the descriptions would be available for export, but they wouldn't need to be propagated.

**Comment by songy23** [comment]
> Another idea is to add a class that contains a TagKey and a description, say ViewTagKey, and then change the columns field in View from type List<TagKey> to List<ViewTagKey>. Then the descriptions would be available for export, but they wouldn't need to be propagated.

Yeah that's what I'm suggesting, or we could use a `Map<TagKey, String>` instead of `List<TagKey>`. In stats library, description will only be used when defining columns for a `View`. I'm not sure if this is worth changing the `View` data model though, if it's ok to export a hard-coded description for `TagKey`s.

**Comment by sebright** [comment]
> I'm not sure if this is worth changing the View data model though, if it's ok to export a hard-coded description for TagKeys.

That makes sense.  We can wait to add a description when we need it.

**Comment by sebright** [comment]
@songy23 Can this issue be closed now that the StackDriver exporter has been released with hard-coded TagKey descriptions?

**Comment by songy23** [comment]
Sure, we can reopen this issue if there's a need to customize the description of LabelDescriptor.
