### ISSUE TITLE
Move RPC measure and view constants out of the API library.

### ISSUE THREAD

**Issue by sebright** [census-instrumentation/opencensus-java#705]
The RPC constants aren't needed for the core stats collection functionality, so it would be better to put them in a separate library.

**Comment by songy23** [comment]
AFAIK gRPC needs these constants to be at core library: https://github.com/grpc/grpc-java/blob/master/core/src/main/java/io/grpc/internal/CensusStatsModule.java#L366

**Comment by sebright** [comment]
Why do the constants need to be in the core library?  If we released a new library that depended on opencensus-api, gRPC could depend on both libraries.

**Comment by songy23** [comment]
That's an alternative. I think gRPC is using these constants in their core library, so at least the constants cannot be in the impl.

/cc @zhangkun83

**Comment by zhangkun83** [comment]
It's reasonable to move them out into a separate library.
Please keep the original ones until gRPC has fully switched to the new ones.

**Comment by sebright** [comment]
@zhangkun83 This change would only affect the new API, in opencensus-api.  I think that gRPC would need to migrate to the new API and RPC constants at the same time, since the view type has changed.  The old API and constants will still be available in instrumentation-api.  Would that work for gRPC?

**Comment by zhangkun83** [comment]
Yes, as long as the old API that gRPC is currently using is not affected, it should be fine.
