### ISSUE TITLE
Not AppEngine/Java7-compatible when creating new threads

### ISSUE THREAD

**Issue by zhangkun83** [census-instrumentation/opencensus-java#707]
I found two places where Census creates its own thread, not sure if there is more:
 1. [io.opencensus.impl.internal.DisruptorEventQueue.java](https://github.com/census-instrumentation/opencensus-java/blob/v0.7.0/impl/src/main/java/io/opencensus/impl/internal/DisruptorEventQueue.java#L144)
 2. [io.opencensus.implcore.trace.export.SpanExporterImpl](https://github.com/census-instrumentation/opencensus-java/blob/v0.7.0/impl_core/src/main/java/io/opencensus/implcore/trace/export/SpanExporterImpl.java#L94)

When running in restricted AppEngine (Java 7), gRPC creates the thread through [MoreExecutors.platformThreadFactory()](https://github.com/grpc/grpc-java/blob/v1.7.0/core/src/main/java/io/grpc/internal/GrpcUtil.java#L517). As Census is used in gRPC and expected to be used in AppEngine, it should probably do the same.

/cc @ejona86, @carl-mastrangelo

**Comment by carl-mastrangelo** [comment]
Note that in App engine 8, regular thread creation is fine, and probably should be preferred.
