### ISSUE TITLE
Simplify SampledSpanStore synchronization

### ISSUE THREAD

**Issue by bogdandrutu** [census-instrumentation/opencensus-java#711]
@zhangkun83 proposed this:

You can get rid of the synchronization in this class by changing `samples` to a `ConcurrentHashMap`.
Here and in `registerSpanNamesForCollection()` you can use `putIfAbsent()`:
```java
PerSpanNameSamples perSpanNameSamples = samples.get(spanName);
if (perSpanNameSamples == null && span.getSampleToLocalSpanStore()) {
  perSpanNameSamples = new PerSpanNameSamples();
  PerSpanNameSamples existingSamples = samples.putIfAbsent(spanName, perSpanNameSamples);
  if (existingSamples != null) {
    perSpanNameSamples = existingSamples;
  }
}
```

**Comment by zhangkun83** [comment]
It is not only for simplicity, it also removes a contention on a global lock.

**Comment by bogdandrutu** [comment]
I think ConcurrentHashMap is still a global lock, isn't it?

**Comment by zhangkun83** [comment]
No, it's thread-safe without synchronization.

**Comment by bogdandrutu** [comment]
Read more about ConcurrentHashMap and decided to fix the contention in a different way by using our queue and enqueue the event and let the worker thread to process the event. Main reason is that ConcurrentHashMap is optimized for intensive writes but our behavior is read intense.

**Comment by zhangkun83** [comment]
ConcurrentHashMap may be optimized for intensive writes, but it doesn't necessarily mean read performance is bad? Less writes is actually preferable because it means lower chance of falling back to the slow path.

Using a queue sounds more complex and there is always a question about its size management.

**Comment by bogdandrutu** [comment]
We need not only to protect the Map we also need to protect each Bucket and fields in each bucket. Will get more complicated to do that on the critical path.
