### ISSUE TITLE
Specify the behavior when ViewManager.getView() is called for unregistered views

### ISSUE THREAD

**Issue by songy23** [census-instrumentation/opencensus-java#718]
Currently in our implementation, if someone called `ViewManager.getView()` for an unregistered view, an `IllegalArgumentException` will be thrown: https://github.com/census-instrumentation/opencensus-java/blob/master/core_impl/src/main/java/io/opencensus/implcore/stats/StatsManager.java#L52. 

However, this API might be simpler to use if we return null for unregistered views instead. Users could simply check for null instead of trying to deal with unchecked exceptions.

Also, as @sebright pointed out, 

> Indicating that a view isn't registered would become even more important if we ever added ViewManager.unregisterView.

See more discussion at: https://github.com/census-instrumentation/opencensus-java/pull/713/commits/37ffb47fc4c7cdc0f57d2f71ed6e202218d3abd0#diff-453a0897e016f2c5fe149602aba1e353R198

**Comment by sebright** [comment]
We will probably need to support unregistering views, so we should return null, or at least throw a checked exception.
