### ISSUE TITLE
Version 1.0 aka stability

### ISSUE THREAD

**Issue by adriancole** [census-instrumentation/opencensus-java#725]
This is a tracking issue for things that are needed imho before we call things api stable

- [ ] minimum instrumentation (servlet filter, apache http client, jax-rs, mysql interceptor)
- [ ] multiple propagation formats (ex b3, trace-context, aws)
- [x] multiple exporters (ex zipkin, stackdriver, xray)
- [ ] version marked 1.0 some sort of compat policy (ex like [guava](https://github.com/google/guava#important-warnings))

Stretch points (adrian's list)
- [ ] at least one non-google APM vendor involved
- [ ] akka instrumentation (aka lovely stroll to mordor)
- [ ] in-process compat with Brave (ex brave can read census trace data)

**Comment by songy23** [comment]
Requirements in this issue have already been fulfilled.
