### ISSUE TITLE
zipkin exporter not available on maven central

### ISSUE THREAD

**Issue by hsyed** [census-instrumentation/opencensus-java#731]
'io.opencensus:opencensus-exporter-trace-zipkin:0.7.0' -- not available.

**Comment by bogdandrutu** [comment]
Hi Hassan,

I just pushed a snapshot 0.8.0-SNAPSHOT of that artifact today. It will get to 0.8.0 which is scheduled early next week.

Sorry for the inconvenience.

**Comment by bogdandrutu** [comment]
Here is the PR that exports it https://github.com/census-instrumentation/opencensus-java/pull/733 and it will be available early next week in our new release.

**Comment by hsyed** [comment]
Thanks ! look forward to it.

**Comment by bogdandrutu** [comment]
0.8.0 is out and includes the zipkin exporter.
