### ISSUE TITLE
Enforce size limit in TagContext serialization and deserialization methods.

### ISSUE THREAD

**Issue by sebright** [census-instrumentation/opencensus-java#761]
See https://github.com/census-instrumentation/opencensus-specs/issues/12. TagContextBinarySerializer.toByteArray should throw a TagContextSerializationException when the serialized size of its input would be larger than 8192 bytes, and TagContextBinarySerializer.fromByteArray should throw a TagContextDeserializationException when its input is over 8192 bytes.

**Comment by songy23** [comment]
Leave this issue open to keep trace of https://github.com/census-instrumentation/opencensus-specs/issues/12#issuecomment-344798450.
