### ISSUE TITLE
Remove one of the two code coverage checks (Codecov or Coveralls)

### ISSUE THREAD

**Issue by sebright** [census-instrumentation/opencensus-java#791]
The two coverage checks are very similar, so we should decide which one to use and remove the other.

**Comment by songy23** [comment]
I would prefer to leave Codecov and remove Coverall, since Codecov has all the information that Coverall has, and it's a little disturbing that Coverall keeps sending notifications on each new commit.

**Comment by sebright** [comment]
I agree.  I don't like how the Coveralls comments clutter PRs.
