### ISSUE TITLE
ExecutorInstrumentationIT > currentContextExecutor FAILED due to time out

### ISSUE THREAD

**Issue by songy23** [census-instrumentation/opencensus-java#793]
I've run into this test failure in travis build (https://travis-ci.org/census-instrumentation/opencensus-java/jobs/299408138):

io.opencensus.contrib.agent.instrumentation.ExecutorInstrumentationIT > currentContextExecutor FAILED
    org.junit.runners.model.TestTimedOutException: test timed out after 60000 milliseconds
        at java.lang.Object.wait(Native Method)
        at java.lang.Object.wait(Object.java:502)
        at io.opencensus.contrib.agent.instrumentation.ExecutorInstrumentationIT.currentContextExecutor(ExecutorInstrumentationIT.java:204)

Consider increasing the test timeout?

**Comment by sebright** [comment]
This looks like the error from #540 (https://github.com/census-instrumentation/opencensus-java/issues/540#issuecomment-325842353).  Maybe the issue occurs with Java 7 and 8.

**Comment by songy23** [comment]
Yes it seems the old issue appears again (however the later build succeeded). Will close this issue if we don't see this in the next few days.

**Comment by sebright** [comment]
I'll reopen the old issue, since it has some debugging notes.

**Comment by ubschmidt2** [comment]
#798 fixes an obvious synchronization issue in the test. I'm closing this for now. Let's reopen if this should surface again.
