### ISSUE TITLE
Gradle warning in contrib-agent

### ISSUE THREAD

**Issue by bogdandrutu** [census-instrumentation/opencensus-java#825]
> Task :opencensus-contrib-agent:shadowJar
The SimpleWorkResult type has been deprecated and is scheduled to be removed in Gradle 5.0. Please use WorkResults.didWork() instead.

**Comment by ubschmidt2** [comment]
This seems fixed with https://github.com/johnrengelman/shadow/commit/f41ba29d0b838c7b80388fc9d1daf37c49e00a40. Will upgrade to new release version once available.
