### ISSUE TITLE
Consider refining trace examples and README

### ISSUE THREAD

**Issue by HailongWen** [census-instrumentation/opencensus-java#842]
Currently we have 3 trace examples: `MultiSpansTracing`, `MultiSpansContextTracing` and `MultiSpansScopedTracing`. Execute these examples just yield nothing. The examples themselves are correct, but there is no sign of any success or failure in the output - which is confusing to users.

2 issues are found related to this issue:
1. the interval for collecting batch span export(`EXPORTER_SCHEDULE_DELAY_MS`) is by default 2s and the examples run pretty fast so no spans actually got exported. In test, sleeping for some time helped.
1. default sampler set sampling probability to 1e-4. The span added in the examples are rarely sampled. In test, explicitly changing the parameter helped.

IMHO, we should either add instruction to clear the expected behavior and known issues, or refine the examples so that they can yield meaningful output.

**Comment by songy23** [comment]
Examples have been moved to opencensus.io.
