### ISSUE TITLE
Add stats zpages

### ISSUE THREAD

**Issue by bogdandrutu** [census-instrumentation/opencensus-java#856]
We should add 2 zpages for stats:
* rpcz - where we display interval stats for all rpcs.
* statsz - where we display view data for all registered views (cumulative, interval, etc).

**Comment by bogdandrutu** [comment]
What is the status of this?

**Comment by songy23** [comment]
RpcZ is almost done. For now the Java RpcZ looks exactly the same as Go RpcZ (though some stats are not supported in Java):

Java RpcZ:
![rpcz](https://user-images.githubusercontent.com/10536136/36054671-8eac56d4-0dac-11e8-85c5-7c22b46f0979.png)

Go RpcZ:
![rpcz-go](https://user-images.githubusercontent.com/10536136/36054692-a6e6420a-0dac-11e8-8cf2-f107ab38002c.png)

**Comment by bogdandrutu** [comment]
I would be happy if you can sort by method names.

**Comment by songy23** [comment]
Sure, will do.

**Comment by bogdandrutu** [comment]
Don't really know what your app looks like, but you may have a conversion problem in the sizes because sending 1MB to create a table seems a lot.

**Comment by songy23** [comment]
You're right - fixed the conversion. The input/output stats become too small to be displayed though, we might consider changing input/output to kb/s or even bytes/s. 

Created https://github.com/census-instrumentation/opencensus-go/issues/437 to follow up.

**Comment by bogdandrutu** [comment]
This is how I would see the "statsz" page:
1) Display all register views using something similar with the directory path in file systems:
**grpc.io/client/started_count/cumulative
grpc.io/server/started_count/cumulative
opencensus.io/http/client/started_count/cumulative**
For these set of views will initially display the root directories:
**grpc.io
opencensus.io**
When click on grpc.io we display:
**grpc.io/client
grpc.io/server**

2) Display all measures sorted by name and we include things like: name, description, units, type (optional). Optional: the number of measurements recorded for each measure.

**Comment by songy23** [comment]
I think we need another table to display the stats for registered views. My thought is when we click on a view name (e.g. **grpc.io/client/roundtrip_latency/cumulative**), the stats on that view should be displayed in a table at the bottom of the page, e.g. tag values, sum/count/histogram.
