### ISSUE TITLE
Consider using a Builder pattern for creating Stackdriver exporter

### ISSUE THREAD

**Issue by songy23** [census-instrumentation/opencensus-java#872]
Since there are a lot of parameters to the constructor of Stackdriver exporter, factory pattern seems less desirable for creating exporter. Considering changing to a builder pattern to make the API easier to use.

**Comment by sebright** [comment]
Maybe we could add a StackDriver configuration class, with an AutoValue builder, and have a single factory method that takes an instance of that class.

**Comment by songy23** [comment]
Sounds great. I post PR https://github.com/census-instrumentation/opencensus-java/pull/896 using the AutoValue.Builder approach.
