### ISSUE TITLE
Consider using Google DPE bot to auto update dependencies

### ISSUE THREAD

**Issue by songy23** [census-instrumentation/opencensus-java#892]
Refer to https://github.com/GoogleCloudPlatform/repository-gardener#adding-the-bot-to-your-repository-googlers-only for details.

An example PR on how this works: https://github.com/GoogleCloudPlatform/java-docs-samples/pull/946

**Comment by HailongWen** [comment]
Done some reading. Seems that it only support maven for now. Might need some extra work to adapt it to our gradle project.

**Comment by songy23** [comment]
Closing, DPE bot doesn't support Gradle yet.
