### ISSUE TITLE
Improve Zipkin status tag names

### ISSUE THREAD

**Issue by jcd2** [census-instrumentation/opencensus-java#904]
https://github.com/census-instrumentation/opencensus-java/blob/817f27b7f96df5b5c10db16e01899bf2ee7f095b/exporters/trace/zipkin/src/main/java/io/opencensus/exporter/trace/zipkin/ZipkinExporterHandler.java#L63

"error" would be better for STATUS_CODE because Zipkin treats that tag specially if it is set.

We used opencensus.status_description instead of census.status_description for STATUS_DESCRIPTION in Go, it would be good to make that the same too.

**Comment by adriancole** [comment]
in zipkin the "error" tag is special. In some cases it is a duplicate copy of another tag. For example. http.status_code=500 will also be error=500 unless there's a better error message (sometimes there is).

**Comment by esukram** [comment]
Can you please label this issue w/ `hacktoberfest` so it qualifies for this participation?

Thanks

**Comment by adriancole** [comment]
PS this shouldn't be closed, the associated PR only renames the tags. it doesn't address the "error" tag which is important for dependency aggregation and display.

**Comment by adriancole** [comment]
easy way: when you know the status is error, copy the same value to the name "error"
