### ISSUE TITLE
Http propagation support for multiple formats

### ISSUE THREAD

**Issue by bogdandrutu** [census-instrumentation/opencensus-java#908]
OpenCensus is committed to support multiple HTTP propagation formats:
* Zipkin (b3 format)
* Stackdriver (x-cloud-trace-context)
* etc.

In order to scale to the number of formats that OpenCensus will eventually support, it is easier to have an independent contrib-http-util package with all the supported formats. 

The initial API can look like this:

```
public final class HttpPropagationUtil {
  /**
   * Returns the SD format.
   */
  public static TextFormat cloudTraceContextFormat();

  /**
   * Returns the b3-format.
   */
  public static TextFormat b3Format();

  // In the future we can add "multiFormat(List<TextFormat> extractors, TextFormat injector);"
  // which is able to read from more formats and writes into one format.
  // This can be used when users want to make the transition from an old format to the new
  // TraceContext format.
}
```

The core API will only have support for the new TraceContext format.

**Comment by adriancole** [comment]
Made comment on the other issue  but removing b3 and leaving an unstable
trace-context format as only choice is cutting off nose to spite the face.

B3 is supported by a large order of libraries and sites that are not
zipkin. It is already configured to pass through intermediaries and many
only use logging but use B3 format. It is the only well defined stable
format out there, and has many different companies who care about it.

Making this hard to reach will not improve maintenance as it doesnt change,
but it will reduce the ability to use it easily in 3rd party tools.

So, yeah up to you but I think doing this with B3 is much different
decision than doing this with cloud trace. I think it is a mistake to
equate the two.

On the api design, some formats cannot be instantiated statically also, as
they need other context such as host identification, or have configuration.
I wouldnt expect the propagation format to be able to work as a static
function class forever, though would for these.

**Comment by adriancole** [comment]
On api design probably best to have interface and registry such as java
service loader. The interface can expose a key for the format. This could
be an option relatively easy for pluggability.

Ex

B3Format extends SomeGenericInterface {

  String type() {
    return "b3";
  }

  ...

}

Then a format could even be internal class (if this is the concern) but
still visible and available for use via dynamic lookup.

I have also heard folks ask about a "detecting format" in jaeger for
example who use both B3 and x-uber.
Sometimes you cant affect your ingress (ex current version of envoy, cloud
foundry etc.. even when they change, sites take a long time to update). If
census decides to remove B3 it becomes less viable as an alternative to
other tools out there today.

**Comment by HailongWen** [comment]
/cc @adriancole

My initial thought is to use a name-based reflection and service loader to dynamically load the class, like the way Hadoop initialize different `FileSystem`: 
if user want to access a file through path `http://abc.txt`
* user call `FileSystem.get("http://abc.txt");` to acquire the `FileSystem` implementation for scheme `http`
* Hadoop will first lookup `fs.http.impl` in the conf for the impl class name; if not defined, it will use service loader to scan who claims to provide `http` support.([link](https://github.com/apache/hadoop/blob/0780fdb1ebdddd19744fbbca7fb05f8fe4bf4d28/hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/FileSystem.java#L3304))
* user access file through `fileSystem.open()`, etc.

So what about we do it like this?
```java
B3Format extends TextFormat {
  String type() {
     return "b3";
  }
}
```

```java
public final class HttpPropagationUtil {
  /**
   * Returns the {@link TextFormat} which supports the specified {@param textFormatName}.
  public static TextFormat getTextFormat(String typeName) {
     // 1. try find class name in system property 
     // 2. if null, try service loader with the typeName.
     // 3. use reflect to create class.
  }
}
```

to use in instrumented code:
```java
TextFormat b3TextFormat = HttpPropagationUtil.getTextFormat("b3");
TextFormat cloudTraceTextFormat = HttpPropagationUtil.getTextFormat("cloudtrace");
```

**Comment by HailongWen** [comment]
Also I think we could leave B3 and whatever we have now in impl_core for default support. New text format could be put in contrib-http-util so they won't have to upgrade census if they want text format only. 

With this we could have
* Default support for B3 without config.
* Extra support by putting jar in class path. (Again, no config).
* Use -Dopencensus.http.propagation.Xxx in system property to workaround/hotfix a defective TextFormat implementation.

**Comment by adriancole** [comment]
I would be careful about reflection especially with java 9, as a lot of
things don't work nice (though this might).

Iterating across all service loader instances isn't terrible.. has worked
in the past, though obv folks should be able to explicitly configure
something https://github.com/Netflix/denominator#third-party-providers

Anyway, something like this is good because at least in B3 the propagation
format is much wider than the exporter (should be separate for this
reason). At the same time formats that are coupled, such as cloud trace,
can be packaged with an exporter

**Comment by adriancole** [comment]
>
>
>    - Default support for B3 without config.
>    - Extra support by putting jar in class path. (Again, no config).
>    - Use -Dopencensus.http.propagation.Xxx in system property to
>    workaround/hotfix a defective TextFormat implementation.
>
> I'd caveat "http" but all else sounds good. For example, routinely people
use same format for http and other RPC (until something interferes with
this like JMS constraints). That said could be fair to say something is
using "http" format even if it isn't http.

There's a choice to make about how to access the B3 format.. whatever that
is, I'd mark the api experimental as we will eventually have switching
concerns which might make things fragile.

**Comment by bogdandrutu** [comment]
@HailongWen we should simply add in the PropagationComponent an API:

```
abstract TextFormat getB3Format();
```

In the PropagationComponentImpl you return the real implementation. In the NoopPropagationComponent return a NoopTextFormat.

The PropagationComponent is already loaded with reflection via the TraceComponent so you don't have to implement anything about loading. When we want to change we will change how the TraceComponent is loaded.

**Comment by HailongWen** [comment]
@bogdandrutu so only B3 format will be accessed from core through `PropagationComponent`, and other format will be put in `HttpPropagationUtil`, right?

**Comment by bogdandrutu** [comment]
Yes and HttpPropagationUtil will be in that separate package
