### ISSUE TITLE
Inconsistent naming for exporters

### ISSUE THREAD

**Issue by rakyll** [census-instrumentation/opencensus-java#925]
StackdriverStatsExporter contains stats in the name even though the trace exporter (StackdriverExporter) doesn't.

Names should consistent. Use io.opencensus.exporter.trace.stackdriver.StackdriverTraceExporter instead.

**Comment by bogdandrutu** [comment]
Please make the change and deprecate the old function name.

**Comment by HailongWen** [comment]
@bogdandrutu do we need to maintain backward compatibility for this class?

**Comment by sebright** [comment]
I think we should leave the old class and deprecate it, though it could just call the methods on the new class.

**Comment by bogdandrutu** [comment]
@HailongWen better safe then sorry. I think what @sebright proposed is correct.

**Comment by bogdandrutu** [comment]
We still have inconsistency between method names:
CreateAndRegisterWithProjectId // trace
CreateWithProjectId // stats

We should fix this as well. if you fix in the trace the advantage is that we just change the names without deprecation because the new class was never released.

**Comment by songy23** [comment]
Now all factory methods in StackdriverStatsExporter are also called [CreateAndRegister](https://github.com/census-instrumentation/opencensus-java/blob/master/exporters/stats/stackdriver/src/main/java/io/opencensus/exporter/stats/stackdriver/StackdriverStatsExporter.java#L162)*.

CreateWithProjectId is an outdated term in StackdriverStatsExporter README. I'll update README to use the new method names (https://github.com/census-instrumentation/opencensus-java/issues/895).
