### ISSUE TITLE
Improve SD trace exporter to comply with SD Trace API v2 limitation.

### ISSUE THREAD

**Issue by HailongWen** [census-instrumentation/opencensus-java#926]
op: https://github.com/census-instrumentation/opencensus-java/pull/923#issuecomment-355426943

SD trace exporter should comply with the limitation in [Trace API v2](https://cloud.google.com/trace/docs/reference/v2/rpc/google.devtools.cloudtrace.v2), and drop items as needed:
> Each attribute's key can be up to 128 bytes long.
> You can have up to 32 attributes per span.
> You can have up to 32 annotations and 128 message events per span.
> You can have up to 128 links per Span.
> You have have up to 32 attributes per link.
> You can have up to 4 attributes per Annotation.

**Comment by bogdandrutu** [comment]
I think this is lower priority because the limitations are enforced in the server anyway for SD. So the only benefit will be that  we send less data. I am not suggesting to not implement this but lower the priority.

**Comment by bogdandrutu** [comment]
This is something we are not going to enforce on the client side unless will be requested, we prefer the backend like SD to do the dropping.
