### ISSUE TITLE
Add a changelog.

### ISSUE THREAD

**Issue by sebright** [census-instrumentation/opencensus-java#945]
A changelog file would simplify the release process by allowing us to describe each user-visible change in the same PR that updates the code.  Then we could copy all entries for the new version into the GitHub release description.  The file would also be useful for viewing the changes for multiple versions at once.

**Comment by adriancole** [comment]
I kindof like using github's release feature (add noted to a tag), as
naturally anchors etc. But either way is cool

**Comment by sebright** [comment]
How could we use the release feature?  Is there a way to add notes to the next release incrementally?

**Comment by adriancole** [comment]
It is tag based so not sure you can prepare notes before release
collaboratively. Good point. Maybe someone at github knows..
