### ISSUE TITLE
Release 0.11.1

### ISSUE THREAD

**Issue by bogdandrutu** [census-instrumentation/opencensus-java#951]
One of our customer found a critical bug in the "X-cloud-trace-context" header https://github.com/census-instrumentation/opencensus-java/pull/950. We need to do a patch release that includes this fix.

**Comment by HailongWen** [comment]
PR #956 merged for the release. Initial deployment done. Commencing release.

**Comment by HailongWen** [comment]
Release done. Opened #958 to trace the version bump of readmes and build files.
