### ISSUE TITLE
Remove Window from View

### ISSUE THREAD

**Issue by ramonza** [census-instrumentation/opencensus-java#995]
As discussed with @bogdandrutu we should implement Window removal for Java as described in https://github.com/census-instrumentation/opencensus-specs/issues/47

**Comment by songy23** [comment]
Just to clarify: is this to remove the `Window` type or just `Interval` window?

**Comment by ramonza** [comment]
In Go, we only had Interval and Cumulative Window types so since there's only a single window type we just assumed Cumulative and remove Window altogether.

**Comment by songy23** [comment]
I see, I think this is the case for Java as well.
